### ISSUE TITLE
{HORUSEC_CLI} Config file not found `Error: ^D 25l`

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/horusec#1007]
**What happened**:

The https://github.com/fike/horusec-action action is returning error since the 2.7.0 version release.

```
Version:          v2.7.0
Git commit:       077d21bd195b65502713073f18f811a400f1d33a
Built:            Tue Feb 08 12:09:48 2022
Distribution:     normal
time="2022-02-09T02:07:25Z" level=warning msg="{HORUSEC_CLI} Config file not found"
Error: ^D
25l
✔ The folder selected is: [/github/workspace]. Proceed? [Y/n]: Y|


25htime="2022-02-09T02:07:25Z" level=warning msg="{HORUSEC_CLI} Error when ask if can run prompt question.: \nPlease use the command below informing the directory you want to run the analysis: \nhorusec start -p ./[^D]"
Usage:
  horusec start [flags]

Examples:
horusec start
```

It still happens on 2.7.1 version

**What you expected to happen**:

- I expected the action to still work as expected since it's using the command line from the documentation to install, and then run the horusec start command: `horusec start -D -e="true" -p="./" --ignore="..."`

**How to reproduce it (as minimally and precisely as possible)**:

- Fork the action and try running the main workflow manually adding a `workflow_dispatch` trigger.

**Anything else we need to know?**:

It seemed related to the `horusec-config.json` file, but even creating it empty or with an empty list, I received an error message about a a parse problem: `Error on get config file path." error="While parsing config: json: cannot unmarshal array into Go value of type map[string]interface {}"`

You can check the historic here, as I run the action daily: https://github.com/GuillaumeFalourd/useful-actions/actions/workflows/horusec.yml?page=2 

The problem started on February 8th, when the 2.7.0 version was released.

**Environment**:
- Horusec version (use `horusec version`): 2.7.0 and newer
- Operating System: Ubuntu
- Network plugin / Tool and version (if this is a network-related / tool bug): -
- Others: -

**Comment by matheusalcantarazup** [comment]
> It seemed related to the `horusec-config.json` file, but even creating it empty or with an empty list, I received an error message about a a parse problem: `Error on get config file path." error="While parsing config: json: cannot unmarshal array into Go value of type map[string]interface {}"`

The contents of the configuration file should have at lest an empty json `{}` and not a list. Can you please try to change and check if the error persist?

It was unclear to me whether in your scenario the config file exists or not. In this case the log reported that the configuration file was not found, did the file exist or not?

From the logs you sent, the workflow failure is not related to the reading of the configuration file, but to process the prompt input during, it would be interesting for the workflow to use the `-p` flag for this question prompt not to appear and crash the workflow.

**Comment by GuillaumeFalourd** [comment]
Hi @matheusalcantarazup 

I made some more tests [here](https://github.com/GuillaumeFalourd/horusec-action/actions), using a `horusec-config.json` with only `{}` inside it and the error still persists.

I also update the command used from `horusec start -D -e="true" -p ./` as suggested in the logs and I was still getting an error.

The last error I got was:

```
Version:          v2.7.1
Git commit:       815c7fbe1a7a25010287787bec2c2e5[6](https://github.com/GuillaumeFalourd/horusec-action/runs/5407665643?check_suite_focus=true#step:4:6)48[7](https://github.com/GuillaumeFalourd/horusec-action/runs/5407665643?check_suite_focus=true#step:4:7)0d56d
Built:            Mon Feb 14 12:5[9](https://github.com/GuillaumeFalourd/horusec-action/runs/5407665643?check_suite_focus=true#step:4:9):[12](https://github.com/GuillaumeFalourd/horusec-action/runs/5407665643?check_suite_focus=true#step:4:12) 2022
Distribution:     normal
25l
Error: ^D
Usage:
  horusec start [flags]

Examples:
horusec start

25htime="2022-03-03T13:28:05Z" level=warning msg="{HORUSEC_CLI} Error when ask if can run prompt question.: \nPlease use the command below informing the directory you want to run the analysis: \nhorusec start -p ./[^D]"
```

I suggest to fork the [fike/horusec-action](https://github.com/fike/horusec-action) repository to perform some tests, it will be easier to reproduce those errors.

**Comment by matheusalcantarazup** [comment]
This seems a problem with the action and not the cli.

I fork the action as you suggested and added a a [echo debug](https://github.com/matheusalcantarazup/horusec-action/blob/main/entrypoint.sh#L5) to show which arguments the entrypoint script is receiving from action, and as you can see [here](https://github.com/matheusalcantarazup/issue-1007/runs/5408330452?check_suite_focus=true#step:4:9) the entrypoint don't receive any argument. So, since the `-p` flag is not passed to start command, a prompt is showed asking the directory that the analysis should be executed, and since there is no response for this prompt the workflow fails.

**Comment by GuillaumeFalourd** [comment]
What I find strange is that the action was working as expected until the release 2.7.0.

Literally the day this version was released, the action started to break: (I was testing it on a daily basis here https://github.com/GuillaumeFalourd/useful-actions/actions/workflows/horusec.yml?page=2)

Could this be a coincidence?

**Comment by matheusalcantarazup** [comment]
> What I find strange is that the action was working as expected until the release 2.7.0 (and the action script hasn't been updated in months).
> 
> Literally the day this version was released, the action started to break: (I was testing it on a daily basis here https://github.com/GuillaumeFalourd/useful-actions/actions/workflows/horusec.yml?page=2)
> 
> Could this be a coincidence?

This is really strange, I don't see any related change that could break this action. I also tested the v2.7 version without running inside a workflow and work as expected, so i think that could be coincidence. 

One think that can be related is that the v2.7.0 was released with an [update of the library](https://github.com/ZupIT/horusec/pull/739) that we use to show this prompt, from a user perspective there is no change with this update, but something could be changed when running on Github workflows for example.


> Note that the `-p` flag is passed in the [action workflow file as action input (args)](https://github.com/matheusalcantarazup/issue-1007/blob/master/.github/workflows/test.yaml), and then used in the `entrypoint.sh` action file afterwards.

Yeah, but this arguments configuration is not passed to `entrypoint,sh` as I mentioned before.

**Comment by GuillaumeFalourd** [comment]
`Yeah, but this arguments configuration is not passed to entrypoint.sh as I mentioned before.`

For what I checked in the [entrypoint.sh](https://github.com/fike/horusec-action/blob/main/entrypoint.sh), the arguments are passed through the `$*` syntax. Everything looks good to me from this point of view 🤔 

Anyway, the best solution would maybe to create an official action in the https://github.com/ZupIT/horusec repository, for the Team to maintain and guarantee it works as expected 👍🏼

**Comment by matheusalcantarazup** [comment]
> For what I checked in the [entrypoint.sh](https://github.com/fike/horusec-action/blob/main/entrypoint.sh), the arguments are passed through the `$*` syntax. Everything looks good to me from this point of view

Yeah for me too, but as I mentioned on the comment above this is not working as expected. [I also set the arguments field](https://github.com/matheusalcantarazup/issue-1007/blob/master/.github/workflows/test.yaml#L16) to pass the `-p` flag but the `entrypoint.sh` script  [receive an empty argument](https://github.com/matheusalcantarazup/issue-1007/runs/5408330452?check_suite_focus=true#step:4:9).



> Anyway, the best solution would probably be to create an official action in the https://github.com/ZupIT/horusec repository, for the Team to maintain and guarantee it works as expected 👍🏼

This is definitely true. We have a [working in progress](https://github.com/ZupIT/horusec-action) implementation, fell free to try to use and find possible bugs (will certainly have bugs)

**Comment by matheusalcantarazup** [comment]
I'm closing this issue since there is no problem with cli, and we already the #981 to track the implementation of an official horusec action. Fell free to open a new issue and thanks for quickly responses.
