### ISSUE TITLE
Add nerdctl as cli containerization tool

### ISSUE THREAD

**Issue by osodracnai** [ZupIT/horusec#1062]
**What would you like to be added**:

i have found [nerdctl](https://github.com/containerd/nerdctl) and after using it for some time i'm pretty satisfied with the results. 

**Why is this needed**:

Today horusec only uses docker as containerization tool, as docker now is a paid tool to use on mac or windows i think it would be a good idea to have another option to use besides that.
Nerdctl also under containerd org, so i think it would not have the same issue as docker to become paid some time.

I got some time to work on it if it's necessary.

**Comment by wiliansilvazup** [comment]
Hello @osodracnai I hope you are well.

This is great idea, we'll add in us backlog for implement in the future tnks \o/
