### ISSUE TITLE
invalid mount config for type \"bind\": invalid propagation mode: private"

### ISSUE THREAD

**Issue by DomZZ** [ZupIT/horusec#1063]
**What happened**:
time="2022-04-21T12:03:32+02:00" level=warning msg="{HORUSEC_CLI} During execution we found some pr
oblems:"

time="2022-04-21T12:03:32+02:00" level=error msg="Error while running tool OwaspDependencyCheck: Er
ror response from daemon: invalid mount config for type \"bind\": invalid propagation mode: private
"
time="2022-04-21T12:03:32+02:00" level=error msg=" Error while running tool Trivy: trivy config cmd
: Error response from daemon: invalid mount config for type \"bind\": invalid propagation mode: pri
vate"
time="2022-04-21T12:03:32+02:00" level=error msg=" Error while running tool Semgrep: Error response
 from daemon: invalid mount config for type \"bind\": invalid propagation mode: private"
time="2022-04-21T12:03:32+02:00" level=error msg=" Error while running tool SecurityCodeScan: Error
 response from daemon: invalid mount config for type \"bind\": invalid propagation mode: private"
time="2022-04-21T12:03:32+02:00" level=error msg=" Error while running tool DotnetCli: Error respon
se from daemon: invalid mount config for type \"bind\": invalid propagation mode: private"
time="2022-04-21T12:03:32+02:00" level=error msg=" Error while running tool NpmAudit: Error respons
e from daemon: invalid mount config for type \"bind\": invalid propagation mode: private"
time="2022-04-21T12:03:32+02:00" level=error msg=" Error while running tool YarnAudit: Error respon
se from daemon: invalid mount config for type \"bind\": invalid propagation mode: private"

**What you expected to happen**:
No such errors

**How to reproduce it (as minimally and precisely as possible)**:
Command line used :
horusec_win_amd64.exe start -p="H:\Dev\Sources\ConfigurationAPITests" -l="H:\Dev\Logs\Horusec" --config-file-path="horusec-config.json" -o="json" -O="./output.json" --information-severity=true --log-level=debug

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`): 2.71
- Operating System: Windows Server 2019
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by wiliansilvazup** [comment]
hello @DomZZ tnks for you feedback.

I tested the same command on a windows machine and it worked fine, could you tell me if you have any more information that we can use to debug?
