### ISSUE TITLE
running horusec docker on Windows, error while checking if docker is running

### ISSUE THREAD

**Issue by DomZZ** [ZupIT/horusec#1068]
**What happened**:
I get the following error in the output
H:\Dev\Tools\Horusec>docker run -v "H:\Dev\Sources\ConfigurationAPITests":/src horuszup/horusec-cli:latest horusec start -p /src -P="H:\Dev\Sources\ConfigurationAPITests" -l="H:\Dev\Logs\Horusec" --config-file-path="/src/horusec-config.json" -o="json" -O="./output.json" --information-severity=true --log-level=debug
time="2022-04-27T05:25:03Z" level=debug msg="{HORUSEC_CLI} Config file running on path: /src/horusec-config.json"
time="2022-04-27T05:25:03Z" level=debug msg="Set log file to /C:\\Users\\DOMINI~1.BOY\\AppData\\Local\\Temp\\horusec-2022-04-15-09-40-16.log"
**Error: exit status 1
time="2022-04-27T05:25:04Z" level=error msg="{HORUSEC_CLI} Error when check if docker is running." error="error during connect: Get "http://docker:2375/v1.24/containers/json": dial tcp: lookup docker on 192.168.229.2:53: server misbehaving"**
Usage:
  horusec start [flags]

Examples:
horusec start

Flags:
  -t, --analysis-timeout int                 The timeout threshold for the Horusec CLI wait for the analysis to complete. The minimum time is 10 (default 600)
  -a, --authorization string                 Authorization token to use on Horusec server. Read more: https://docs.horusec.io/docs/tutorials/how-to-create-an-authorization-token (default "00000000-0000-0000-0000-000000000000")
  -C, --certificate-path string              Path to certificate of authority. Example -C="example/ca.crt"
  -P, --container-bind-project-path string   Project path in host to be used on Docker when running Horusec inside a container
  -c, --custom-rules-path string             Path with custom rules that should be used by Horusec engine
  -D, --disable-docker                       Run Horusec without docker. If enabled it will only run the following tools: horusec-csharp, horusec-kotlin, horusec-java, horusec-kubernetes, horusec-leaks, horusec-javascript, horusec-dart, horusec-nginx
  -G, --enable-commit-author                 Enable to search commit author of vulnerabilities
      --enable-git-history                   Run Gitleaks and search for vulnerabilities in all git history of the project https://github.com/zricethezav/gitleaks
  -w, --enable-owasp-dependency-check        Run Owasp Dependency Check tool https://github.com/jeremylong/DependencyCheck
  -j, --enable-shellcheck                    Run ShellCheck tool https://github.com/koalaman/shellcheck
  -F, --false-positive strings               Ignore a vulnerability by hash and set it to be false positive. Example -F="hash1, hash2"
      --headers stringToString               Custom headers to send on request to Horusec API. Example --headers='{"X-Auth-Service": "value"}' (default [])
  -h, --help                                 help for start
  -u, --horusec-url string                   The Horusec server address to send analysis results (default "http://0.0.0.0:8000")
  -i, --ignore strings                       Paths to ignore in the analysis. Example: -i="/path/to/ignore, **/*_test.go, **/assets/**" (default [*tmp*,**/.vscode/**])
  -s, --ignore-severity strings              The level of vulnerabilities to ignore in the output ("LOW"|"MEDIUM"|"HIGH"). Example: -s="LOW, HIGH" (default [INFO])
  -I, --information-severity                 Enable information severity vulnerabilities. Information vulnerabilities can contain a lot of false positives
  -S, --insecure-skip-verify                 Disable the certification validation. PLEASE, try not to use it
  -O, --json-output-file string              Output file to write analysis result. This flag should be used with --output-format
  -o, --output-format string                 Output format of analysis ("text"|"json"|"sonarqube"). For json and sonarqube --json-output-file is required
  -p, --project-path string                  Path to run an analysis. If this value is not passed, Horusec will ask if you want to run the analysis in the current directory (default "/")
  -n, --repository-name string               Send repository name to Horusec server, by default sends the actual directory name (default "/")
  -r, --request-timeout int                  The timeout threshold for the request to the Horusec server. The minimum time is 10 (default 300)
  -e, --return-error                         Return exit code 1 if found vulnerabilities. Default value is false (exit code 0)
  -R, --risk-accept strings                  Ignore a vulnerability by hash and set it to be risk accept. Example -R="hash1, hash2"
      --show-vulnerabilities-types strings   Show vulnerabilities by types ("Vulnerability"|"Risk Accepted"|"False Positive"|"Corrected"). Example --show-vulnerabilities-types="Vulnerability, Risk Accepted" (default [Vulnerability])

Global Flags:
      --config-file-path string   Path of the configuration file (default "/horusec-config.json")
  -l, --log-file-path string      Path of log file (default "/tmp/horusec-2022-04-27-05-25-03.log")
      --log-level string          Set log level ("panic"|"fatal"|"error"|"warn"|"info"|"debug"|"trace") (default "info")

H:\Dev\Tools\Horusec>

**How to reproduce it (as minimally and precisely as possible)**:
docker run -v "H:\Dev\Sources\ConfigurationAPITests":/src horuszup/horusec-cli:latest horusec start -p /src -P="H:\Dev\Sources\ConfigurationAPITests" -l="H:\Dev\Logs\Horusec" --config-file-path="/src/horusec-config.json" -o="json" -O="./output.json" --information-severity=true --log-level=debug

**Anything else we need to know?**:
N/A

**Environment**:
- Horusec version (use `horusec version`): 2.7.1
- Operating System: Windows
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by wiliansilvazup** [comment]
hello @DomZZ tnks for you feedback.

I tested the same command on a windows machine and it worked fine, could you tell me if you have any more information that we can use to debug?
