### ISSUE TITLE
PDF Report

### ISSUE THREAD

**Issue by lcaoppit** [ZupIT/horusec#1070]
**What would you like to be added**:
Is it possible to build a new feature where we can get a PDF report about a project's scan?

**Why is this needed**:
For executive reasons. Sometimes we need to send a report to CISO/CTO to show how are our security maturity and how is manage the vulnerabilities

**Comment by wiliansilvazup** [comment]
hello @lcaoppit currently onlly output enabled are: `json, text, sarif, sonarqube`, this is great idea and I'll add in us backlog tnks :)

**Comment by jtabone16** [comment]
@wiliansilvazup i just ran the CLI tool and can't figure out how to output to those types
