### ISSUE TITLE
Auth with ambassador 405 Method Not Allowed

### ISSUE THREAD

**Issue by Zeeshan50522** [ZupIT/horusec#1071]
i am using horusec with ambassador controller but while authentication i'm getting  405 Method Not Allowed.

![ambassdor](https://user-images.githubusercontent.com/34584842/166266449-95bc5291-add5-4582-b63f-f6dee9aa0ff5.png)

working fine with nginx ingress controller but issue with ambassador controller

**Comment by wiliansilvazup** [comment]
hello @Zeeshan50522 tnks for your feedback.

You can sent for us more information ? ambassador configuration, environments variables, etc...
Currently the only way we tested was actually using nginx we need some more information to know if it is possible to use this new way of use.
