### ISSUE TITLE
Unable to host horusec-platform on ec2. Tried all the three types of installation but it is not working for remote host.

### ISSUE THREAD

**Issue by tusharjupiter** [ZupIT/horusec#1073]
**What happened**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`):
- Operating System:
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by tusharjupiter** [comment]
<img width="1157" alt="Screenshot 2022-05-04 at 10 26 30 PM" src="https://user-images.githubusercontent.com/103413875/166737954-7c53eb99-d47e-4493-8d8e-66567e52f461.png">
Horusec Version

**Comment by jlmartins-sf** [comment]
Hi @tusharjupiter, could you post your steps that you did?
Btw, can you confirm if in your postgresql instance there is at least, two databases, analytic_db and horusec_db?

**Comment by wiliansilvazup** [comment]
i'll close this issue for now, any update you can reopen :)
