### ISSUE TITLE
Website and docs page not working

### ISSUE THREAD

**Issue by lagerfeuer** [ZupIT/horusec#1074]
**What happened**:
The linked website (horusec.io) including the docs pages do not load. 
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/5903157/167143653-9e83d5b2-3e49-4b10-b2ba-eea4672af4eb.png">
<img width="645" alt="image" src="https://user-images.githubusercontent.com/5903157/167144118-5d5d03ec-4e9f-4eb4-90cd-c542b3492966.png">

**What you expected to happen**:
The website loads and I can read about the project and the docs.

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://horusec.io

**Anything else we need to know?**
Chrome install is stock (no add-ons)

**Environment**:
- Operating System: MacOS Monterey
- Others: Tested under Firefox and Chrome

**Comment by osodracnai** [comment]
i'm able to access the website, but i'm located in Brazil so this maybe be a region block. Anyone can reproduce?

**Comment by wiliansilvazup** [comment]
hello @lagerfeuer tnks for this report.

I'll sent this thread for us team to check more details tnks :)
