### ISSUE TITLE
Running horusec without Docker

### ISSUE THREAD

**Issue by simongottschlag** [ZupIT/horusec#108]
**What would you like to be added**:
Add the ability to run horusec without Docker. We are trying to move away from the Docker requirement as much as possible and would make it much easier to run horusec in a pipeline that doesn't have access to it.

**Why is this needed**:
More and more projects are moving away from using Docker / docker socket and not requiering as much permissions.

**Comment by wiliansilvazup** [comment]
Hello, how are you @simongottschlag  ?
We are preparing ourselves to have a vision of Horusec without using the docker as you may have seen we have some CLI's that are already being carried out thinking about this scenario such as Horusec-Java, Horusec-Kotlin, Horusec-Leaks.
But our short-term goal is to propose a good quality in the delivery of results that Horusec is able to achieve in our analyzes and for this objective to be achieved the docker will be necessary in the short term at the moment. Maybe in Q1 (2021) we can't start thinking about possible solutions =)

**Comment by simongottschlag** [comment]
Hi @wiliansilvazup!

Sounds great :) Thank you for the information.
