### ISSUE TITLE
Dashboard docker image all-in-one does not update

### ISSUE THREAD

**Issue by matheusbloise** [ZupIT/horusec#1080]
**What happened**:

My dashboard does not update after run cli, the only thing that's working is vulnerabilities section, everything is upon the latest docker image version.

take a look bellow what's going!

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/46876171/173066806-14c60ab1-da3f-44d4-8e18-f3ca715f48a9.png">
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/46876171/173066015-afd9f03b-17a0-44cd-8516-42d9bebbbe38.png">

**How to reproduce it (as minimally and precisely as possible)**:

how i said before that, the only thing that's sync is just the vulnerability section, that's mean the cli is reaching the dashboard api

```
docker run --network horusec -v /var/run/docker.sock:/var/run/docker.sock \                            
        -v $(pwd):/src/horusec \                                                    
        horuszup/horusec-cli:latest horusec start -a <HORUSEC-TOKEN> -u http://<HORUSEC-API-HOST> -p /src/horusec -P $(pwd)
```

```
docker run --privileged --name horusec-all-in-one -p 8000:8000 -p 8001:8001 -p 8003:8003 -p 8004:8004 \
        -p 8005:8005 -p 8006:8006 -p 8043:8080 -d horuszup/horusec-all-in-one:latest
```

**Comment by wiliansilvazup** [comment]
hello @matheusbloise tnks for your contribuition 

Please you can sent more information of logs in the services `horusec-api` and `horusec-analytic` maybe your service is not healthy or another configuration failed

**Comment by wiliansilvazup** [comment]
@matheusbloise i look again and you is using horusec-all-in-one this image, not receive more updates, change to normal format how is describe in us [documentation](https://docs.horusec.io/docs/web/installation/)

**Comment by matheusbloise** [comment]
quick feedback for you guys, put back all-in-one on the road, because is really boring up need to configure every dependency separated

all in one is good for dev or small business on qa envrionments, you indication doesn’t work well, there are a lot problems with dependencies and scripts, for a while a will be using just the cli check, but would be really good have the complete local environment.
