### ISSUE TITLE
Your docs / website is broken

### ISSUE THREAD

**Issue by james-green-affinity** [ZupIT/horusec#1102]
I have tried on different browsers although on my phone it seems to work.

![image](https://user-images.githubusercontent.com/91469943/176496979-d272e23a-e208-41e8-9ba3-2102e04c62f8.png)

**Comment by wiliansilvazup** [comment]
here for me it's ok
![image](https://user-images.githubusercontent.com/63816070/177131642-bb7747cd-7ee3-4b73-9c7c-2ce76765ada3.png)
