### ISSUE TITLE
Integration with DefectDojo is not working

### ISSUE THREAD

**Issue by RP-omayrzanata** [ZupIT/horusec#1108]
**What would you like to be added**:
The integration with Defect Dojo is not working correctly, when trying to import JSON

error message: 
An exception error occurred during the report import:invalid literal for int() with base 10: ''

**Comment by wooch82** [comment]
I use dd-import and have no issues with import. Can you provide a report you tried to import?

**Comment by guilhermepaulozup** [comment]
Closed since this issue was solved by DefectDojo [#6563](https://github.com/DefectDojo/django-DefectDojo/pull/6563)
