### ISSUE TITLE
Building docker scan images locally

### ISSUE THREAD

**Issue by shizzgar** [ZupIT/horusec#147]
Hy guys!
I've tested my project after updating horusec-cli to v1.4.2
And it's works like a charm!

But I have a question.
What should i do to forse cli to build scan images locally without requesting to your dockerhub repo?

**What would you like to be added**:
Feature to build scan images locally...

**Why is this needed**:
It can be useful for some companies in order to increase the level of security...

By the way, if you show me the vector,
I think, i can do it by myself. 
I not very well in GO, but i have some expirence in Python.
So i want to try!

Many thanks in advance!

**Comment by nathannascimentozup** [comment]
Hi @shizzgar 
The golang docker sdk has a https://godoc.org/github.com/docker/docker/client#Client.ImageBuild functionality and we have the dockerfiles in the project, but I'm thinking if it should be a CLI feature or just a documentation exaplaning how to build the images using our repository and the sh scripts.

Its a good point of discussion considering the new limitation of the dockerhub

**Comment by shizzgar** [comment]
Oh, my..
This is awesome, how did i miss this one?
I' will try to play with what just right now!

**Comment by nathannascimentozup** [comment]
I believe that adding go code would be the best alternative.
The `--build-docker-images` flag could be created in the start command and this flag would build the images needed to perform analysis (after detecting the languages).
