### ISSUE TITLE
Building docker scan images in Azure DevOps: ## [error] Docker exec fail with exit code 127

### ISSUE THREAD

**Issue by natanefabene** [ZupIT/horusec#154]
**What happened**:
I'm trying to use the image: horuszup / horusec-cli in my Azure DevOps pipeline.
However the error occurs: "## [error] Docker exec fail with exit code 127"

**How to reproduce it (as minimally and precisely as possible)**:
The code I am using in my yaml is basic:
"trigger:
  - master
jobs:
- job: horusec_security
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: 'horuszup / horusec-cli' "

**Anything else we need to know?**:
Setting up Yaml in Azure DevOps

**Environment**:
- Horusec version (use `horusec version`): Latest
- Operating System: ubuntu-latest and ubustu-16.04
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by nathannascimentozup** [comment]
has azure devops the option to elevate job permission or something else related to job privilege?

**Comment by wiliansilvazup** [comment]
hello @natanefabene 

You can try run with this configuration please?
```
pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: curl -fsSL https://horusec.io/bin/install.sh | bash && horusec start -p ./
```

**Comment by natanefabene** [comment]
Hello thank you very much. With the Wiilian Script it worked.
