### ISSUE TITLE
Dashboard (https://horusec.zup.com.br/)

### ISSUE THREAD

**Issue by javixeneize** [ZupIT/horusec#164]
Hi

The documentation refers to a dashboard where you can see your reports, it points to https://horusec.zup.com.br/

However this site returns a 403 - forbidden. Is there any way to see the report generated?

Thanks

**Comment by wiliansilvazup** [comment]
The endpoint https://horusec.zup.com.br is not enable!

If you work at ZupIT, call me on the chat to help you better!
