### ISSUE TITLE
Link to open file with vulnerability

### ISSUE THREAD

**Issue by wiliansilvazup** [ZupIT/horusec#17]
**What would you like to be added**:
Add link of file with vulnerability when print output in terminal

File to edit
https://github.com/ZupIT/horusec/blob/master/horusec-cli/internal/controllers/printresults/print_results.go#L241

**Comment by eftakhairul** [comment]
I am interested to work on this. .

**Comment by igorreiszup** [comment]
Hi @eftakhairul thanks for your interest! 
We're looking forward to have the quality of life feature of print the path of a file and the user's editor (VSCode or any other) be able to open the file in the exact location. This is obviously very hard, because there's a lot of editors out there, but we think that if you get any of them to work, it will already be amazing!

**Comment by marcoscostazup** [comment]
@eftakhairul, are you still working on that? If you aren't I would like to

**Comment by MarcosFelipeBC** [comment]
Hi @eftakhairul! Are you still working on this issue?

**Comment by eftakhairul** [comment]
@MarcosFelipeBC  go for it.

**Comment by MarcosFelipeBC** [comment]
Hi @igorreiszup, on VSCode printing the absolute path of some file or directory is enough to get a link. Could I just change the way you print the vulnerability file path now from relative to absolute path?

**Comment by wiliansilvazup** [comment]
Thank you for taking an interest in the project.
I believe that just adding the absolute path can already be a possible test, yes!
For this you can go to the file that is in the location:
https://github.com/ZupIT/horusec/blob/master/horusec-cli/internal/controllers/printresults/print_results.go#L241
And change only in the print of type `Text` to have a junction of `pr.configs.GetProjectPath()`+`vulnerability.File`
Good Luck!

**Comment by wiliansilvazup** [comment]
Fixed on PR #156
