### ISSUE TITLE
Makefile scripts not interpreting env variables

### ISSUE THREAD

**Issue by henriquemoraeszup** [ZupIT/horusec#174]
**What happened**:
Horusec reported a hardcoded password in a Makefile that was using an external env variable. One example error below:
```
Language: Leaks
Severity: HIGH
Line: 19
Column: 11
SecurityTool: HorusecLeaks
Confidence: HIGH
File: Makefile
Code: GIT_REMOTE=***github.com/ZupIT/ritchie-cli
Details: Password found in a hardcoded URL
A password was found in a hardcoded URL, this can lead to not only the leak of this password but also a failure point to some more sophisticated CSRF and SSRF attacks. Check CWE-352 (https://cwe.mitre.org/data/definitions/352.html) and CWE-918 (https://cwe.mitre.org/data/definitions/918.html) for more details.
Type: Vulnerability
ReferenceHash: e6b6b327efae6f8f8a846b603f143cbaad7c1c288b7f58b41605097e6e8456f5
```

The actual code implementation is
`GIT_REMOTE=https://$(GIT_USERNAME):$(GIT_PASSWORD)@github.com/ZupIT/ritchie-cli`
Where `GIT_PASSWORD` is not previously declared anywhere in the project

**What you expected to happen**:
Injected env variables should not present a security risk

**How to reproduce it (as minimally and precisely as possible)**:
Create a makefile that exposes a url with password substituted by an env
i.e.: `GIT_REMOTE=https://$(GIT_USERNAME):$(GIT_PASSWORD)@github.com/ZupIT/ritchie-cli`

**Environment**:
- Horusec version (use `horusec version`): v1-5-0
- Operating System: Linux x64
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by nathannascimentozup** [comment]
Hi @henriquemoraeszup thanks for reporting. 

apparently this is a false positive. you can ignore this vulnerability by adding the reference hash in the horusec-config.json file.

https://docs.horusec.io/referencia/cli#configuracoes-da-cli
