### ISSUE TITLE
Add NodeJS support

### ISSUE THREAD

**Issue by nathannascimentozup** [ZupIT/horusec#2]
**What would you like to be added**:

Add horode-cli NodeJS support, you can use following some of these instructions:
Using horusec-engine:
    * https://github.com/ZupIT/horusec/blob/master/HOWTO.md#adding-new-tool-using-horusec-engine
Using existing tool:
    * https://github.com/ZupIT/horusec/blob/master/HOWTO.md#adding-security-tool

**Comment by wiliansilvazup** [comment]
Fixed on PR #153
