### ISSUE TITLE
horusec-manager inicializa com pagina em branco

### ISSUE THREAD

**Issue by jcsferraz** [ZupIT/horusec#222]
**horusec-manager inicializa com a página em branco **:

** Após executados os passos abaixo conforme orientação para instalação local o horusec manager carrega com página em branco
- git clone https://github.com/ZupIT/horusec.git
- make install**:

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`): 1.6.1
- Operating System: Ubuntu 20.04.1 kernel 5.4.0-1029-aws
- Others: docker-compose 1.25.0 , docker 20.10.1

**Comment by jcsferraz** [comment]
**Duvidas:  é obrigatório as definições das variáveis abaixo que possam impactar na subida do projeto :**

WARNING: The HORUSEC_SMTP_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The HORUSEC_SMTP_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_API variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_ANALYTIC variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_ACCOUNT variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_ENDPOINT_AUTH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_BASE_PATH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_KEYCLOAK_REALM variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_MICROFRONTEND_PUBLIC_PATH variable is not set. Defaulting to a blank string.
WARNING: The REACT_APP_HORUSEC_MANAGER_THEME variable is not set. Defaulting to a blank string.

**Comment by wiliansilvazup** [comment]
Olá @jcsferraz 

Obrigado por relatar o ocorrido!

Você sabe me dizer se alterou alguma variavel de ambiente no [docker-compose.yaml](https://github.com/ZupIT/horusec/blob/master/deployments/docker-compose.yaml) ou na máquina local?

**Comment by jcsferraz** [comment]
Olá!

Não alteramos nenhuma variável no docker-compose.yaml

Apenas fizemos o seguinte :

- git clone https://github.com/ZupIT/horusec.git
- make install

E anterior à estes passos instalamos o docker-compose na maquina local.

**Comment by wiliansilvazup** [comment]
Estranho! Rodei aqui e não tive nenhum problema!
Qual é a sua versão do ubuntu?
Outra questão você consegue me passar o qual é a saída no comando `docker ps -a`?

**Comment by jcsferraz** [comment]
claro

**Comment by jcsferraz** [comment]
`5ff528054caa   horuszup/horusec-webhook:latest    "./horusec-webhook-m…"   11 seconds ago   Restarting (2) 1 second ago                                                                                                                  horusec-webhook

57e8c0530636   horuszup/horusec-account:latest    "./horusec-account-m…"   11 seconds ago   Up 10 seconds                                                                                                                                horusec-account

0aff2b859ada   horuszup/horusec-api:latest        "./horusec-api-main"     11 seconds ago   Up 10 seconds                                                                                                                                horusec-api

a279b5ae99ca   horuszup/horusec-analytic:latest   "./horusec-analytic-…"   11 seconds ago   Up 10 seconds                                                                                                                                horusec-analytic

d39e796187ac   horuszup/horusec-auth:latest       "./horusec-auth-main"    11 seconds ago   Up 10 seconds                                                                                                                                horusec-auth

774ee06556a5   horuszup/horusec-messages:latest   "./horusec-messages-…"   11 seconds ago   Restarting (2) 2 seconds ago                                                                                                                 horusec-messages

50f41d7342ee   horuszup/horusec-manager:latest    "/docker-entrypoint.…"   12 seconds ago   Up 11 seconds                  80/tcp, 0.0.0.0:8043->8080/tcp                                                                                horusec-manager

268c4570dad6   rabbitmq:3-management              "docker-entrypoint.s…"   12 seconds ago   Up 11 seconds                  4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   rabbit

f9eaa7763104   postgres:12                        "docker-entrypoint.s…"   12 seconds ago   Up 11 seconds                  0.0.0.0:5432->5432/tcp `

**Comment by jcsferraz** [comment]
Me informe se ficou ruim a 'view' que forneci..

**Comment by wiliansilvazup** [comment]
E você está tentando acessar o manager na porta 8043 certo?

**Comment by jcsferraz** [comment]
`horuszup/horusec-webhook:latest    "./horusec-webhook-m…"   11 seconds ago   Restarting (2) 1 second ago                                                                                                                  horusec-webhook`

`horuszup/horusec-account:latest    "./horusec-account-m…"   11 seconds ago   Up 10 seconds                                                                                                                                horusec-account`

`horuszup/horusec-api:latest        "./horusec-api-main"     11 seconds ago   Up 10 seconds                                                                                                                                horusec-api`

`horuszup/horusec-analytic:latest   "./horusec-analytic-…"   11 seconds ago   Up 10 seconds                                                                                                                                horusec-analytic`

`horuszup/horusec-auth:latest       "./horusec-auth-main"    11 seconds ago   Up 10 seconds                                                                                                                                horusec-auth`

`horuszup/horusec-messages:latest   "./horusec-messages-…"   11 seconds ago   Restarting (2) 2 seconds ago                                                                                                                 horusec-messages`

`horuszup/horusec-manager:latest    "/docker-entrypoint.…"   12 seconds ago   Up 11 seconds                  80/tcp, 0.0.0.0:8043->8080/tcp                                                                                horusec-manager`

`rabbitmq:3-management              "docker-entrypoint.s…"   12 seconds ago   Up 11 seconds                  4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   rabbit`


`postgres:12                        "docker-entrypoint.s…"   12 seconds ago   Up 11 seconds                  0.0.0.0:5432->5432/tcp                                                                                        postgresql`

**Comment by jcsferraz** [comment]
> E você está tentando acessar o manager na porta 8043 certo?

Sim ! correto ! Se quiser, pode observar em :

`http://54.161.72.226:8043/auth`

**Comment by wiliansilvazup** [comment]
O erro está acontecendo por que o endpoint é diferente do padrão `127.0.0.1`
Os serviços que o manager se comunica são:
* API
* ANALYTIC
* ACCOUNT
* AUTH

No seu caso seria alterar as variáveis de ambiente para
```
$ export REACT_APP_HORUSEC_ENDPOINT_API="http:\/\/54.161.72.226:8000"
$ export REACT_APP_HORUSEC_ENDPOINT_ANALYTIC="http:\/\/54.161.72.226:8005"
$ export REACT_APP_HORUSEC_ENDPOINT_ACCOUNT="http:\/\/54.161.72.226:8003"
$ export REACT_APP_HORUSEC_ENDPOINT_AUTH="http:\/\/54.161.72.226:8006"
```

**Comment by wiliansilvazup** [comment]
veja que neste exemplo acima fiz o escape das barras por ser uma string talvez a forma que você adicione essas variáveis de ambiente não seja necessário

**Comment by wiliansilvazup** [comment]
após adicionar as variáveis de ambiente tente rodar o comando `make install` novamente !

**Comment by jcsferraz** [comment]
perfeito
fazendo agora.
!!!

**Comment by jcsferraz** [comment]
> veja que neste exemplo acima fiz o escape das barras por ser uma string talvez a forma que você adicione essas variáveis de ambiente não seja necessário


> O erro está acontecendo por que o endpoint é diferente do padrão `127.0.0.1`
> Os serviços que o manager se comunica são:
> 
>     * API
> 
>     * ANALYTIC
> 
>     * ACCOUNT
> 
>     * AUTH
> 
> 
> No seu caso seria alterar as variáveis de ambiente para
> 
> ```
> $ export REACT_APP_HORUSEC_ENDPOINT_API="http:\/\/54.161.72.226:8000"
> $ export REACT_APP_HORUSEC_ENDPOINT_ANALYTIC="http:\/\/54.161.72.226:8005"
> $ export REACT_APP_HORUSEC_ENDPOINT_ACCOUNT="http:\/\/54.161.72.226:8003"
> $ export REACT_APP_HORUSEC_ENDPOINT_AUTH="http:\/\/54.161.72.226:8006"
> ```

`funcionou, seria possivel adicionar essas informações para ajudar outras pessoas ?? qual seria a senha e password padrao a serem utilizados apos subir o manager ??`

**Comment by jcsferraz** [comment]
- como seria para utilizar HTTPS nesse endpoint ??? Existe alguma outra variavel para configurar para definir HTTPS ??

**Comment by jcsferraz** [comment]
Para adicionar novos usuários no 'manager' é necessária parametrizar alguma variável de email  e rodar o 'make install' novamente ?

**Comment by wiliansilvazup** [comment]
> > veja que neste exemplo acima fiz o escape das barras por ser uma string talvez a forma que você adicione essas variáveis de ambiente não seja necessário
> 
> > O erro está acontecendo por que o endpoint é diferente do padrão `127.0.0.1`
> > Os serviços que o manager se comunica são:
> > ```
> > * API
> > 
> > * ANALYTIC
> > 
> > * ACCOUNT
> > 
> > * AUTH
> > ```
> > 
> > 
> > No seu caso seria alterar as variáveis de ambiente para
> > ```
> > $ export REACT_APP_HORUSEC_ENDPOINT_API="http:\/\/54.161.72.226:8000"
> > $ export REACT_APP_HORUSEC_ENDPOINT_ANALYTIC="http:\/\/54.161.72.226:8005"
> > $ export REACT_APP_HORUSEC_ENDPOINT_ACCOUNT="http:\/\/54.161.72.226:8003"
> > $ export REACT_APP_HORUSEC_ENDPOINT_AUTH="http:\/\/54.161.72.226:8006"
> > ```
> 
> `funcionou, seria possivel adicionar essas informações para ajudar outras pessoas ?? qual seria a senha e password padrao a serem utilizados apos subir o manager ??`

O usuário e senha padrão estão no [Readme](https://github.com/ZupIT/horusec#default-development-account)

**Comment by wiliansilvazup** [comment]
> * como seria para utilizar HTTPS nesse endpoint ??? Existe alguma outra variavel para configurar para definir HTTPS ??

Não é necessário voce pode alterar essas mesmas variaveis para adicionar o https

**Comment by wiliansilvazup** [comment]
> Para adicionar novos usuários no 'manager' é necessária parametrizar alguma variável de email e rodar o 'make install' novamente ?

Quando você entrar na plataforma você pode acessar usando a conta padrão que o horusec cria ou criar sua própria conta na tela inicial. Outros usuários vão poder criar suas contas no mesmo lugar e você pode [convidá-los para sua organização](https://docs.horusec.io/referencia/manager/gestao-de-conta).

**Comment by wiliansilvazup** [comment]
Vamos adicionar essa configuração nas documentações obrigado novamente !
