### ISSUE TITLE
Horusec Manager

### ISSUE THREAD

**Issue by wesleybsb1** [ZupIT/horusec#324]
I know it's a simple question, I already did the code analysis, but I didn't understand how to access Horusec-Manager, is it your central server or a web server that is installed on the local machine?

**Environment**:
- Horusec version (use `horusec version`):  1.8.0
- Operating System: Kali

**Comment by nathanmartinszup** [comment]
Hello @wesleybsb1 .

If you want to test locally you can use our makefile with the command `make install`, that way we will run a compose and expose the web service that can be accessed at: `http://localhost:8043`.
 
We also have helm charts for each web service needed to access the menager, these can be found within the deployments folder for the following services:

   - horusec-account
   - horusec-auth
   - horusec-analytic
   - horusec-api
   - horusec-manager
   
   
Here is a link to our docs:

https://docs.horusec.io/v/v1-eng/

**Comment by douglasluizm** [comment]
I have a similar issue. I was able to run the make install and seems that the containers are running correctly, but when I try to access http://myserverip:8043, it shows an empty page (with Horusec favicon). 

If I try to use curl, I can see the following message inside the html: **"You need to run javascript to run this app"**.

Where do I need to run javascript, which container?

I am using amazon linux with 8043 port open.

**Comment by tiagosoaresolist** [comment]
> I have a similar issue. I was able to run the make install and seems that the containers are running correctly, but when I try to access http://myserverip:8043, it shows an empty page (with Horusec favicon).
> 
> If I try to use curl, I can see the following message inside the html: **"You need to run javascript to run this app"**.
> 
> Where do I need to run javascript, which container?
> 
> I am using amazon linux with 8043 port open.

Same here. Blank screen.

**Comment by lucasbrunozup** [comment]
Hello @douglasluizm and @tiagosoaresolist

Can you please send me the output content of the `docker logs horusec-manager` command? and also, send me, if you have, some content in the "**console**" tab of the browser, when trying to access the service through it.

**Comment by douglasluizm** [comment]
[docker logs horusec-manager.txt](https://github.com/ZupIT/horusec/files/6009881/docker.logs.horusec-manager.txt)
![Console](https://user-images.githubusercontent.com/23419172/108503499-3f23c580-7293-11eb-8c30-b3f1b5ad9c5d.jpg)

I've tried with different browsers (Chrome, Edge, IE). Currently using Edge 88.0.705.68

Thanks!

**Comment by tiagosoaresolist** [comment]
Sure!



`177.12.41.150 - - [19/Feb/2021:12:17:51 +0000] "GET /auth HTTP/1.1" 200 3899 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:51 +0000] "GET /static/css/2.e6ac38db.chunk.css HTTP/1.1" 200 21854 "http://horusecip:8043/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:51 +0000] "GET /static/js/2.5229b6b6.chunk.js HTTP/1.1" 200 637087 "http://horusecip:8043/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:51 +0000] "GET /static/js/main.91761d57.chunk.js HTTP/1.1" 200 97996 "http://horusecip:8043/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:51 +0000] "GET /static/css/2.e6ac38db.chunk.css.map HTTP/1.1" 200 29432 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:52 +0000] "GET /favicon.svg HTTP/1.1" 200 13390 "http://horusecip:8043/auth" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:52 +0000] "GET /static/js/2.5229b6b6.chunk.js.map HTTP/1.1" 200 2623539 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"
177.12.41.150 - - [19/Feb/2021:12:17:52 +0000] "GET /static/js/main.91761d57.chunk.js.map HTTP/1.1" 200 190900 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36" "-"`

![image](https://user-images.githubusercontent.com/74270771/108503768-accff180-7293-11eb-8aa0-cbd5ab03a716.png)

**Comment by douglasluizm** [comment]
Also, not sure if related, but the horusec-messages container never started sucessfully, it keeps restarting. I am sending the logs for it as well:

[docker logs horusec-messages.txt](https://github.com/ZupIT/horusec/files/6009977/docker.logs.horusec-messages.txt)

**Comment by tiagosoaresolist** [comment]
Exactly same behavior here `horus-messages` container restarting forever logging the same error.

**Comment by lucasbrunozup** [comment]
I was not able to identify exactly the error, through the information they sent me, however, I was able to make an improvement in the functions that are causing this error, in order to better identify it. We will release this fix, and we ask that you update to the new version and try it again, please.

**Comment by douglasluizm** [comment]
I did a new install but got the same behavior and syntax error in the console (tried different browser, and incognito).

**Comment by lucasbrunozup** [comment]
It's very strange.

Okay, come on, could you check the result of the `api/auth/config` request in the browser's network tab?

**Comment by douglasluizm** [comment]
I am not sure how to check that. When I go to the network tab, I can see the following:

![Screenshot_3](https://user-images.githubusercontent.com/23419172/108515702-22dc5480-72a4-11eb-97ff-76d5d8b27a4a.jpg)

not sure if useful, tbh :) 

I tried to load the swagger (http://horusecip:8043/swagger/index.html) but got the same result.

**Comment by lucasbrunozup** [comment]
![image](https://user-images.githubusercontent.com/69604366/108534994-8b81fc00-72b9-11eb-9ebd-e42fc7b90def.png)
That's right, it's on this tab. However, when you open it, update the page with it open to be able to check all the requests that were made. After that, there is a search field at the top, search for / auth / config, and select one of the options and check the answer on the right side in the "preview" tab.

**Comment by douglasluizm** [comment]
It seems that there is nothing with the words "auth/config" our "auth" or "config", only the files I indicated in my last reply.

**Comment by tiagosoaresolist** [comment]
And JS is enabled in chrome. Same behaviour in Firefox.

![image](https://user-images.githubusercontent.com/74270771/108545144-2c76b400-72c6-11eb-9df8-02e8284dcf45.png)

**Comment by lucasbrunozup** [comment]
What form are you using to install Horusec? are using `make install`? and made any changes to the compose file?

**Comment by douglasluizm** [comment]
I am using "make install" on a fresh new instance (Amazon Linux 2 AMI), and did not change anything on the compose.

**Comment by tiagosoaresolist** [comment]
Same here. Just `git clone` and `make install`. Tested on a fresh Amazon linux EC2 and on my MacOS.

**Comment by lucasbrunozup** [comment]
Okay, so let's check the health of the main services that the manager needs.
What is the result when you try to access the following routes?

Can access directly in the browser, or through `CURL`

http://YOUR_IP:8003/account/health

http://YOUR_IP:8006/auth/health

**Comment by wiliansilvazup** [comment]
@douglasluizm Tudo bem?
Qual é seu sistema operacional?
Qual é a versão do docker e docker-compose?

Se estiver rodando em uma maquina a parte como por exemplo uma VM favor verifique qualquer configuração de firewall e limitações da máquina que foi adicionada

**Comment by douglasluizm** [comment]
boa tarde @wiliansilvazup , tudo bem e você?

Então, estou usando uma instancia na AWS com SO Amazon Linux 2 AMI e para o docker:
Docker version 19.03.13-ce, build 4484c46
docker-compose version 1.26.0, build d4451659

A instancia tem tráfego para fora liberado, e portas 80, 3000, 8003, 8006, 8043 abertas.

**Comment by wiliansilvazup** [comment]
Quando você roda o comando `docker ps -a` qual é o output ? se conseguir tirar um print e nos mandar :)

**Comment by douglasluizm** [comment]
![image](https://user-images.githubusercontent.com/23419172/109034922-e4c9a100-76a6-11eb-89f2-3edb46f5cff4.png)

**Comment by wiliansilvazup** [comment]
como você está utilizando o [docker-compose](https://github.com/ZupIT/horusec/blob/master/deployments/docker-compose.yaml) padrão o serviço de horusec-messages e o serviço horusec-webhook não iram subir e nem funcionar mesmo pelo fato de que o broker não está habilitado por padrão. Então não se preocupe com eles.

Já em relação aos outros serviços você consegue acessar o `http://SEU_IP:8000/swagger/index.html` ? Este é o swagger do serviço horusec-api

**Comment by douglasluizm** [comment]
Eu não tinha liberado esta porta. Depois que liberei consegui acessar o swagger, mas ele retorna o seguinte erro:

`Failed to load API definition.
Errors
 
Fetch errorFailed to fetch http://localhost:8000/swagger/doc.json
Fetch errorPossible cross-origin (CORS) issue? The URL origin (http://localhost:8000) does not match the page (http://ipdainstancia:8000). Check the server returns the correct 'Access-Control-Allow-*' headers.`

Se eu tento um `curl localhost:8000/swagger/index.html` de dentro da instancia, retorna uma pagina sem erro aparente, mas se tento `curl localhost:8043` ele retorna a pagina com o mesmo erro do javascript.

**Comment by lucasbrunozup** [comment]
@douglasluizm este é o comportamente esperado pelo "manager" ao realizar um Curl nele, por ser desenvolvido em React.JS.

**Comment by wiliansilvazup** [comment]
@tiagosoaresolist @douglasluizm 
Vocês podem nos enviar seus e-mails por gentileza ?

**Comment by wiliansilvazup** [comment]
Ou nos envie seu problema através do e-mail horusec@zup.com.br que iremos receber também :)

**Comment by wiliansilvazup** [comment]
@tiagoangelozup @wesleybsb1 
Or send us your problem through the email horusec@zup.com.br which we will also receive :)

**Comment by lucasbrunozup** [comment]
@tiagosoaresolist and @wesleybsb1  

Talking to @douglasluizm , we verified that in his case, it was necessary to inform the environment variables of the "manager". Do you have these variables defined?

**Comment by bright-start** [comment]
After building horusc through docker-compose, visit http://ip : 8043, enter the login page, default account login error, through the view of horusc database, found that there is no initial table structure, where is the initial table structure？

**Comment by wiliansilvazup** [comment]
Hello @bright-start.

What command did you perform to up the horusec services?

**Comment by bright-start** [comment]
> 您好@ bright-start。
> 
> 您执行了什么命令来启动horusec服务？



> Hello @bright-start.
> 
> What command did you perform to up the horusec services?

Now that I have solved the problem, there is a problem with the horusc service started by **docker compose up - d**, but there is no problem with the horusc service built by **make install**

**Comment by bright-start** [comment]
> Hello @bright-start.
> 
> What command did you perform to up the horusec services?

Now that I have solved the problem, there is a problem with the horusc service started by docker compose up - d, but there is no problem with the horusc service built by make install
Thinks.

**Comment by nathannascimentozup** [comment]
> > Hello @bright-start.
> > What command did you perform to up the horusec services?
> 
> Now that I have solved the problem, there is a problem with the horusc service started by docker compose up - d, but there is no problem with the horusc service built by make install
> Thinks.

The make install script executes the database migration. If you run the services by using docker-compode up -d y'll need to run the migration by your own.
