### ISSUE TITLE
horusec-manager envia link inválido para confirmações de novos usuários na plataforma

### ISSUE THREAD

**Issue by jcsferraz** [ZupIT/horusec#340]
**Ao criar novos usuários em nossa plataforma, o link de confirmação do usuário vem no seguinte formato:**:

**http://localhost:8006/api/account/validate/6f6b48ab-ab3f-483f-aa2222-121212112121**:

** O que precisamos fazer para ajustar ?? **

**Environment**:
- Horusec version (use `horusec version`): 1.8.2
- Operating System: Ubuntu 20.04

**Comment by jcsferraz** [comment]
**Estamos usando as seguintes variáveis:**

# export vars for horusec-manager

REACT_APP_HORUSEC_ENDPOINT_API="http:\/\/sec.meuend.com.br:8000"
REACT_APP_HORUSEC_ENDPOINT_ANALYTIC="http:\/\/sec.meuend.com.br:8005"
REACT_APP_HORUSEC_ENDPOINT_ACCOUNT="http:\/\/sec.meuend.com.br:8003"
REACT_APP_HORUSEC_ENDPOINT_AUTH="http:\/\/sec.meuend.com.br:8006"
HORUSEC_MANAGER_URL="http:\/\/sec.meuend.com.br:8043"


#exoort vars for horusec invite users
HORUSEC_SMTP_HOST="email-smtp.us-east-1.amazonaws.com"
HORUSEC_SMTP_ADDRESS="email-smtp.us-east-1.amazonaws.com"
HORUSEC_EMAIL_FROM="horusec@sec.meuend.com.br"
HORUSEC_SMTP_PORT="587"
HORUSEC_SMTP_USERNAME="sssss"
HORUSEC_SMTP_PASSWORD="ssssss"

**Comment by nathanmartinszup** [comment]
Olá @jcsferraz .

Acabei de verificar que se trata de um bug. A url que é gerada está com a rota desatualizada.

Já estamos trabalhando na correção e assim que estiver disponível te retorno para que possa testar novamente.

Muito obrigado pelo feedback.

**Comment by nathanmartinszup** [comment]
Olá novamente @jcsferraz .

Fizemos a correção para o problema reportado, mas para isso será necessário atualizar as seguintes images na versão latest:

horuszup/horusec-manager
horuszup/horusec-messages
horuszup/horusec-auth

Obrigado novamente pelo report.

**Comment by jcsferraz** [comment]
@nathanmartinszup 

Boa tarde!

Nós efetuamos o deploy, usando o 'make install' na ferramenta e continuamos recebendo os links dos invites no seguinte formato :

**http://localhost:8006/api/account/validate/6f6b48ab-ab3f-483f-aa2222-121212112121**

Environment:

    Horusec version (use horusec version): 1.8.3
    Operating System: Ubuntu 20.04


Existe algo que precisamos ajustar definir para valer de fato as modificações ou alterações já efetuadas por vocês ?

**Comment by nathanmartinszup** [comment]
Olá, @jcsferraz.

Segue a resposta na nova issue que você abriu:

https://github.com/ZupIT/horusec/issues/347#issuecomment-781304959

**Comment by jcsferraz** [comment]
Olá @nathanmartinszup 

**Eu removi as imagens localmente :**

horuszup/horusec-manager
horuszup/horusec-messages
horuszup/horusec-auth

**Porém, após removê-las, e rodar o 'make install' novamente não vejo mais a 'organization' que eu criei.**

E capturando o 'erro' no modo 'F12' do navegador eu tenho o seguinte erro : 

**'404 page not found' para o endpoint : "http://sec.meuend.com.br:8003"**
