### ISSUE TITLE
horusec-manager envia link inválido para confirmações de novos usuários na plataforma

### ISSUE THREAD

**Issue by jcsferraz** [ZupIT/horusec#347]
**Ao criar novos usuários em nossa plataforma, o link de confirmação do usuário vem no seguinte formato:**

http://localhost:8006/api/account/validate/6f6b48ab-ab3f-483f-aa2222-121212112121:

Estamos usando as seguintes variáveis:

vars for horusec-manager

REACT_APP_HORUSEC_ENDPOINT_API="http://sec.meuend.com.br:8000"
REACT_APP_HORUSEC_ENDPOINT_ANALYTIC="http://sec.meuend.com.br:8005"
REACT_APP_HORUSEC_ENDPOINT_ACCOUNT="http://sec.meuend.com.br:8003"
REACT_APP_HORUSEC_ENDPOINT_AUTH="http://sec.meuend.com.br:8006"
HORUSEC_MANAGER_URL="http://sec.meuend.com.br:8043"

vars for horusec invite users
HORUSEC_SMTP_HOST="email-smtp.us-east-1.amazonaws.com"
HORUSEC_SMTP_ADDRESS="email-smtp.us-east-1.amazonaws.com"
HORUSEC_EMAIL_FROM="horusec@sec.meuend.com.br"
HORUSEC_SMTP_PORT="587"
HORUSEC_SMTP_USERNAME="sssss"
HORUSEC_SMTP_PASSWORD="ssssss"

Nós efetuamos o deploy, usando o 'make install' na ferramenta e continuamos recebendo os links dos invites no seguinte formato :

http://localhost:8006/api/account/validate/6f6b48ab-ab3f-483f-aa2222-121212112121

Na pratica por si , as imagens abaixo já são atualizadas no processo após o 'make install' correto ?

horuszup/horusec-manager
horuszup/horusec-messages
horuszup/horusec-auth

**Environment**:
- Horusec version (use `horusec version`): 1.8.3
- Operating System: ubuntu 20.04

**Comment by nathanmartinszup** [comment]
Olá, @jcsferraz.

Realizei o teste seguindo o cenário que me passou, tudo ocorreu corretamente.

Acredito que suas imagens ainda estão desatualizadas, pois o compose sempre busca pela latest e você já possuía images com a tag latest localmente.

Seria possível remover as imagens locais do horusec e realizar o make install novamente?

Caso deseje desabilitar a verificação de email, também possuímos uma opção para isso, basta definir a variável de ambiente `HORUSEC_DISABLED_BROKER` como `true`. 

Fico no aguardo da sua resposta, obrigado!

**Comment by jcsferraz** [comment]
Olá @nathanmartinszup 

**Eu removi as imagens localmente :**

horuszup/horusec-manager
horuszup/horusec-messages
horuszup/horusec-auth

**Porém, após removê-las, e rodar o 'make install' novamente não vejo mais a 'organization' que eu criei.**

E capturando o 'erro' no modo 'F12' do navegador eu tenho o seguinte erro : 

**'404 page not found' para o endpoint : "http://sec.meuend.com.br:8003"**

**Comment by nathanmartinszup** [comment]
Bom dia @jcsferraz .

Agora a rota do link de email está correta, mas será necessário alterar a variável de ambiente `HORUSEC_API_URL` para o host referente ao horusec-auth, que no seu caso acredito que seja: `http://sec.meuend.com.br:8006`, dessa forma o `http://localhost:8006` será trocado pelo host informado na variável de ambiente. 

Sobre o erro que encontrou, consegue me passar mais informações? Se possível qual a rota está retornando o erro, como também verificar se os serviços estão rodando.

Fico no aguardo, obrigado!

**Comment by jcsferraz** [comment]
@nathanmartinszup 

**Serviços rodando:**

**CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                                                                                                         NAMES
29d5c6b93d47   rabbitmq:3-management              "docker-entrypoint.s…"   57 seconds ago   Up 55 seconds   4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   rabbit
14cef4eed6d1   postgres:12                        "docker-entrypoint.s…"   57 seconds ago   Up 55 seconds   0.0.0.0:5432->5432/tcp                                                                                        postgresql
fbcca2eadd4a   horuszup/horusec-manager:latest    "/docker-entrypoint.…"   57 seconds ago   Up 55 seconds   80/tcp, 0.0.0.0:8043->8080/tcp**   

Consegue me sugerir alguma maneira de enviar 'imagens' por aqui pra evidênciar as questões de rotas que mencionou ??

Já adicionei a nova VAR 'HORUSEC_API_URL' e volto a fazer as considerações.

**Comment by nathanmartinszup** [comment]
@jcsferraz 

Para que se utilize do web service do horusec é necessário que os seguintes serviços estejam rodando:

- horusec-api
- horusec-auth
- horusec-account
- horusec-analytic
- horusec-manager

Estando todos em pé e mesmo assim o erro continua, você pode estar verificando se em algum dos contêineres está com log de erro.

Também é possível verificar através do inspecionar do navegador na aba network, qual a requisição está retornando o 404.

Recomendo que se possível, execute o make install novamente preenchendo as variáveis informadas anteriormente.

Fico no aguardo do seu retorno.

**Comment by jcsferraz** [comment]
Estou coletando os dados, e já sinalizo novamente por aqui.

**Comment by wiliansilvazup** [comment]
Vou fechar a issue por enquanto mas qualquer novidade você pode abrir novamente que iremos te auxiliar :)
