### ISSUE TITLE
Wrong non-vulnerable line shown in the output

### ISSUE THREAD

**Issue by gabriel-pinheiro** [ZupIT/horusec#389]
**What happened**:
Some rules show the wrong line of code in the "Code: " output.

**What you expected to happen**:
I expect to see the vulnerable line of code in the output.

**How to reproduce it (as minimally and precisely as possible)**:
Create a file like so:
```js
const text = "This line has no vulnerabilities";
alert("This line is vulnerable");
```

And run horusec in it:
`horusec start -T Eslint -p .`

Output:
![DeepinScreenshot_select-area_20210305065911](https://user-images.githubusercontent.com/56726395/110099651-4f9e6a80-7d80-11eb-9d9f-c599ba502aa9.png)

**Anything else we need to know?**:
It happens to rules that start matching with the `\s+` Regex like alert's rule:
`(\s+|^)(alert|confirm|prompt)\(`

As the string starts matching in the \n of the line above, it is the one reported in the output instead of the vulnerable line

**Environment**:
- Horusec version (use `horusec version`): v1.8.3
- Operating System: *
- Network plugin / Tool and version (if this is a network-related / tool bug): None
- Others: None

**Comment by wiliansilvazup** [comment]
Tnks for your report @gabriel-pinheiro !
Well the regex is really wrong! We go analysis here and send feedback later here with the correction :D
