### ISSUE TITLE
Improve report when vulnerabilities were found

### ISSUE THREAD

**Issue by matheusribeirozup** [ZupIT/horusec#419]
**Problem**
When horusec is configured with hashes to ignore false positives and it detects a new vulnerability/false positive, **ALL** cases are listed in the report, which makes it difficult to see the real problem.

**What would you like to be added**:
The horusec report should only list the vulnerabilities/false positives that are **NOT** listed in the tool's configuration.

**Why is this needed**:
This change would make it easier to identify the problem that the horusec is actually complaining about.

**Comment by nathannascimentozup** [comment]
Hi @matheusrcostazup,

I agree with you. We should prioritize the vulnerabilities that was not considered false positive. 
I think we have two solutions for this problem:

1. We create a new flag to show/hide false positive from report
2. We remove some information of the false positive reported on screen and highlight the true vulnerabilities

**Comment by matheusribeirozup** [comment]
Hi @nathannascimentozup thanks for the quick return, I think that both solutions solve the problem. You guys implementing at least one of them is enough :)
PS: you marked the wrong Matheus in the answer haha

**Comment by wiliansilvazup** [comment]
I will close this issue for now as soon as we have any updates on the improvements we will reopen it
