### ISSUE TITLE
cannot start cli tool

### ISSUE THREAD

**Issue by xiaochao** [ZupIT/horusec#420]
I download cli tool by https://horusec.io/bin/latest/mac_x64/horusec.  I got some error messages when i run horusec start

ERRO[0001] {HORUSEC_CLI} Error when check if requirements it's ok!output:   error=
PANI[0001] {HORUSEC_CLI} Missing required DOCKER in min. version 19.03 to start  error="check the requirements for run and try again"
panic: (*logrus.Entry) 0xc000549d50

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000549ce0, 0x0, 0xc000538140, 0x44)
	/home/wilian/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc000549ce0, 0x0, 0xc000fdfab0, 0x1, 0x1)
	/home/wilian/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/home/wilian/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
github.com/ZupIT/horusec/development-kit/pkg/utils/logger.LogPanicWithLevel(0x19e05c6, 0x44, 0x1c28b60, 0xc000097590, 0x0, 0x0, 0x0)
	/home/wilian/go/src/github.com/ZupIT/horusec/development-kit/pkg/utils/logger/logger.go:101 +0x12c
github.com/ZupIT/horusec/horusec-cli/internal/controllers/requirements.(*Requirements).ValidateDocker(0xc000fe85c0)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/internal/controllers/requirements/requirements.go:48 +0x85
github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start.(*Start).validateRequirements(0xc00028bbc0)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start/start.go:180 +0x7e
github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start.(*Start).configsValidations(0xc00028bbc0, 0xc000ff2a00, 0x0, 0x0)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start/start.go:168 +0xed
github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start.(*Start).startAnalysis(0xc00028bbc0, 0xc000ff2a00, 0xc000fdfd80, 0x1744465, 0xc000fe54f4)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start/start.go:154 +0x7a
github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start.(*Start).runE(0xc00028bbc0, 0xc000ff2a00, 0x24af1e8, 0x0, 0x0, 0x0, 0x0)
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/cmd/horusec/start/start.go:134 +0x51
github.com/spf13/cobra.(*Command).execute(0xc000ff2a00, 0x24af1e8, 0x0, 0x0, 0xc000ff2a00, 0x24af1e8)
	/home/wilian/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x246f260, 0x0, 0x24313d8, 0xc00008c058)
	/home/wilian/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/wilian/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/home/wilian/go/src/github.com/ZupIT/horusec/horusec-cli/cmd/horusec/main.go:63 +0x2d

**Comment by nathanmartinszup** [comment]
Hello, @xiaochao.

Horusec has docker as a dependency to run some analysis tools. 
I recommend that if possible, install docker and try again. (https://docs.docker.com/docker-for-mac/install/)

If you do not want to install the docker, we have a flag that disables the dependency.
Just run as follows `horusec start -D true`

This flag will disable several analysis tools, consequently reducing the quality of the analysis.

We are already working to make these requirements clearer in our documentation.

Thanks for the feedback!!

**Comment by xiaochao** [comment]
> https://docs.docker.com/docker-for-mac/install/

Thank you very much. I will try it later.

**Comment by pveerrotwal** [comment]
Hi, I already had docker install with all privileges but still I am facing the docker issue while running HORUSEC, I tried it in both macOS as well in ubuntu still facing issue in both platforms, please check:

Paramvirs-MacBook-Air:ToDoFastAPI-Backend paramvirrotwal$ `horusec start`

WARN[0000] {HORUSEC_CLI} Config file not found          
✔ The folder selected is: [/Users/paramvirrotwal/Downloads/ToDoFastAPI/ToDoFastAPI-Backend]. Proceed? [Y/n]: Y|
ERRO[0002] {HORUSEC_CLI} Your docker version is below of:   error=19.3
Error: docker not found. Please check and try again

**Comment by stlucasgarcia** [comment]
@pveerrotwal The same is currently happening to me, did you find a fix?
