### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by IgorDePaula** [ZupIT/horusec#421]
**What happened**:

I used with my laravel(php) project, and the tool said that my password is hardcoded, but is a validation rule

**What you expected to happen**:
That this not happens
**How to reproduce it (as minimally and precisely as possible)**:
Create a laravel project, and a validation rule with password is required.

**Anything else we need to know?**:
The error and the file

![Captura de tela de 2021-03-27 21-40-56](https://user-images.githubusercontent.com/2833993/112738817-3fc01380-8f45-11eb-8b17-9fd9d5bf4986.png)
![Captura de tela de 2021-03-27 21-40-23](https://user-images.githubusercontent.com/2833993/112738818-43539a80-8f45-11eb-8bf8-ac9b436661fa.png)

**Environment**:
- Horusec version (use `horusec version`): 1.10.1
- Operating System: ubuntu 20.04
- Network plugin / Tool and version (if this is a network-related / tool bug): laravel (php) 8.0
- Others:

**Comment by nathanmartinszup** [comment]
Hi, @IgorDePaula! Sorry for the delay.

We are continually working to reduce the number of false positives and consequently bring a more accurate analysis.
Your feedback will be of great help to us improve!

Until we fix it, you may be using the false positive option from our CLI.

Here is a link to the documentation:

https://horusec.io/docs/cli/resources/#1-configuration-file

An example of setting a false positive in `horusec-config.json` file:

```
{
    "horusecCliFalsePositiveHashes": [
            "ReferenceHash"
    ]
}
```

**Comment by nathanmartinszup** [comment]
Hi @IgorDePaula 

By default, horusec fetches the configuration file from the current location where it is running.

Did you create the file `horusec-config.json` at the root of your project ?

If not, you will need to pass the file location. 

This can be done with the `--config-file-path` flag as follows:

`--config-file-path="/home/example/path/project"`

Config file with the vulnerability hash:
```
{
    "horusecCliFalsePositiveHashes": [
            "288f29c3b5a4a2169254d8acdf6f6a3903ba1d81159f8d82c4e2cfdcd905b91",
            "another hash"
    ]
}
```

After that the vulnerability will continue to be listed, but with the type of false positive and will no longer break the pipeline.

It is possible to see the options of the cli with the following command `horusec help` and also `horusec start --help`.

**Comment by IgorDePaula** [comment]
@nathanmartinszup I thinked that horusec get the config file by default, but I set

![Captura de tela de 2021-04-15 10-58-00](https://user-images.githubusercontent.com/2833993/114881907-ce53e200-9dd9-11eb-9e4a-4c4cba8eb790.png)

**Comment by nathanmartinszup** [comment]
@IgorDePaula 

Also needed pass config file name in path:

`horusec start -p projetos/consulta --config-file-path projetos/consulta/horusec-config.json`

**Comment by IgorDePaula** [comment]
@nathanmartinszup, with config file, the result is same.

![Captura de tela de 2021-04-15 11-48-12](https://user-images.githubusercontent.com/2833993/114889656-afa51980-9de0-11eb-8380-29818970b641.png)
![Captura de tela de 2021-04-15 11-47-48](https://user-images.githubusercontent.com/2833993/114889672-b2077380-9de0-11eb-9678-b9e3f07772e5.png)

**Comment by nathanmartinszup** [comment]
@IgorDePaula 

Your Referecence hash has to be related to the vulnerability.

Change the text `ReferenceHash` in your config file to the ReferenceHash that was returned in the vulnerability.

Like this example:

```
{
    "horusecCliFalsePositiveHashes": [
            "288f29c3b5a4a2169254d8acdf6f6a3903ba1d81159f8d82c4e2cfdcd905b91"
    ]
}
```

It is our way of identifying which vulnerability you want to identify as a false positive.

**Comment by IgorDePaula** [comment]
I wrote this hash on config file, like example, but change the last character "1" for "2" and the result is the same. But the reference hash of final test ends with "1", and not "2".

**Comment by nathanmartinszup** [comment]
@IgorDePaula 

There is no need to change anything in the hash, just copy and paste into the json array.

**Comment by wiliansilvazup** [comment]
@IgorDePaula you can try this command ?
```
horusec start -p . --ignore="**/vendor/**" -O="saida.json" -o="json" --false-positive="288f29c3b5a4ab2169254d8acbf6f6a3903ba1d81159f8d82c4e2cfdcd905b91"
```

**Comment by IgorDePaula** [comment]
@nathanmartinszup I replaced in json file. I'm programmer too.

@wiliansilvazup 
![Captura de tela de 2021-04-15 15-34-37](https://user-images.githubusercontent.com/2833993/114920810-387f7d80-9e00-11eb-86f2-b6f4f2809afe.png)

**Comment by wiliansilvazup** [comment]
In your first picture with json response @IgorDePaula 

you have vulnerability hash: `288f29c3b5a4ab2169254d8acbf6f6a3903ba1d81159f8d82c4e2cfdcf905b91`

And you pass in command in flag: `288f29c3b5a4ab2169254d8acbf6f6a3903ba1d81159f8d82c4e2cfdcd905b91`

See this two hash is not equals .... fix to correctly hash

**Comment by IgorDePaula** [comment]
I understand, I'll try.

**Comment by IgorDePaula** [comment]
@wiliansilvazup Nothing, same result;

**Comment by IgorDePaula** [comment]
![Captura de tela de 2021-04-15 17-46-02](https://user-images.githubusercontent.com/2833993/114936196-78e7f700-9e12-11eb-871d-811524aea784.png)
![Captura de tela de 2021-04-15 17-45-45](https://user-images.githubusercontent.com/2833993/114936207-7b4a5100-9e12-11eb-85ee-3e7727bccc64.png)
![Captura de tela de 2021-04-15 17-45-31](https://user-images.githubusercontent.com/2833993/114936214-7dacab00-9e12-11eb-9a4c-751c2bfd1778.png)

**Comment by wiliansilvazup** [comment]
Your hash is wrong, you need put this hash `288f29c3b5a4ab2169254d8acbf6f6a3903ba1d81159f8d82c4e2cfdcf905b91`

**Comment by IgorDePaula** [comment]
I used the same hash, until I change both to 1234, but the false positive continues.

**Comment by wiliansilvazup** [comment]
The hash IS NOT EQUALS @IgorDePaula :) 

See the last 8 characters in you command ... 
`...cd905b91`
and See last 8 characters in output informmed by horusec analysis 
`...cf905b91`

Please copy hash of analysis of horusec and paste in horusec-config file or in flag

**Comment by wiliansilvazup** [comment]
i will close issue for now, if you need help is possible reopen this issue

**Comment by IgorDePaula** [comment]
Yes, you can close. I follow all instructions, but always show this false positive. I'll forget it, and look another tool.
