### ISSUE TITLE
Disable specific rules from scan

### ISSUE THREAD

**Issue by cynthiabaran** [ZupIT/horusec#422]
**What would you like to be added**:
A feature for disabling a list of rules when you run a scan, so they don't show in the report. Currently you can only specify new custom rules or disable an analyzer entirely, but not specific rules from them.

**Why is this needed**:
Because rules might not applicable in certain environments, users might be interested in filtering out some types of vulnerabilities from the report.

**Comment by nathanmartinszup** [comment]
Hi, @cynthiabaran! Sorry for the delay.

This feature is already in our backlock and it shouldn't take long to be available.

Until then, if any rule is causing problems, we have a way to treat false positives:

Here is a link to the documentation:

https://horusec.io/docs/cli/resources/#1-configuration-file

An example of setting a false positive in `horusec-config.json` file:

```
{
    "horusecCliFalsePositiveHashes": [
            "ReferenceHash"
    ]
}
```

Thanks for sharing your feedback!

**Comment by wiliansilvazup** [comment]
i will close issue for now, if you need help is possible reopen this issue
