### ISSUE TITLE
Attemping to setup horusec on a vm

### ISSUE THREAD

**Issue by Followthevu** [ZupIT/horusec#424]
installed docker and docker compose on new ubuntu vm.

logged into web portal with:
email: dev@example.com
password: Devpass0*

The web app keeps saying something is wrong, however the logs for the containers provide no information

![image](https://user-images.githubusercontent.com/14968409/113777957-c4efb900-96f9-11eb-8cc4-7e5ffcb0b32d.png)

**Comment by nathannascimentozup** [comment]
Hi @Followthevu!

Can you provide us the browser console output? When this error message pops up we expect an output error in the console. This error will show us the path to understand what is going on

**Comment by Followthevu** [comment]
Hey @nathannascimentozup  Thanks for responding so fast.

it looks like the console is trying to reach local host, instead of the IP that the server has.

127.0.0.1:8006/auth/auth/config:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
127.0.0.1:8006/auth/auth/authenticate:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
![image](https://user-images.githubusercontent.com/14968409/113876758-0b8af500-9786-11eb-9650-3cf5f5f5c37f.png)

Was I supposed to configure the server address somewhere?

**Comment by nathannascimentozup** [comment]
Yes, that's the problem!

When you are deploying the manager service you need to specify the hosts of the services. 

this tutorial can help you, take a look:

https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/

**Comment by Followthevu** [comment]
Thank you that worked!, may I suggest a link to that added to setting up the web application instead of a tutorial? Mainly because I never expected setting up on separate host to be a "tutorial" but an actual installation requirement.

**Comment by nathannascimentozup** [comment]
> Thank you that worked!, may I suggest a link to that added to setting up the web application instead of a tutorial? Mainly because I never expected setting up on separate host to be a "tutorial" but an actual installation requirement.

I agree, this tutorial can be a topic in the documentation
