### ISSUE TITLE
sonarqube json export is malformed

### ISSUE THREAD

**Issue by trenerok** [ZupIT/horusec#433]
json export for sonarqube is malformed and can't handled by sonarqube during the import. Tested on sonarqube 8.8 CE

It has a few problems:
 - "filepath" field should be in camel case  like "filePath"
 - textRange properties : can't be with 0 value
 - textRange properties: 
 example:
          "startLine": 93,
          "endLine": 0,
          "startColumn": 35,
          "endColumn": 0
          
 **endLine** and **EndColumn** can not be less then value in the **startLine** and **startColumn**

**Comment by wiliansilvazup** [comment]
Tnks for you report @trenerok, We will look as soon as possible

**Comment by trenerok** [comment]
Thank you @wiliansilvazup
We are really looking forward to the fix

**Comment by trenerok** [comment]
@wiliansilvazup hello,
Found another problem, sometimes Horusec-cli with sonarqube export, create json with minus values..
Please see the screenshot (-29 value):
![image](https://user-images.githubusercontent.com/18612132/115835930-8b1ff180-a41f-11eb-87a1-2a0b82bd7980.png)

**Comment by wiliansilvazup** [comment]
This error will be corrected together with the [issue 438](https://github.com/ZupIT/horusec/issues/438)
