### ISSUE TITLE
minus values in sonarqbue export json.

### ISSUE THREAD

**Issue by trenerok** [ZupIT/horusec#438]
@wiliansilvazup hello,
Found another problem, sometimes Horusec-cli with sonarqube export, create json with minus values..
Please see the screenshot (-29 value):
![image](https://user-images.githubusercontent.com/18612132/115835930-8b1ff180-a41f-11eb-87a1-2a0b82bd7980.png)

_Originally posted by @trenerok in https://github.com/ZupIT/horusec/issues/433#issuecomment-825458670_

**Comment by wiliansilvazup** [comment]
Tnks for your report, we will correct as soon as possible 🚀

**Comment by nathannascimentozup** [comment]
Hi @trenerok thanks for report us the problem.

Could you provide us a code sample where the bug occurs?

**Comment by trenerok** [comment]
Hi @nathannascimentozup,
surely, I took this repo from - https://github.com/mpirnat/lets-be-bad-guys.git

**Comment by nathannascimentozup** [comment]
> Hi @nathannascimentozup,
> surely, I took this repo from - https://github.com/mpirnat/lets-be-bad-guys.git.
> The root folder of this project was specified for scanning

thanks a lot!!
I just opened a PR to fix the bug.

**Comment by wiliansilvazup** [comment]
Fix on version **v1.10.3** of the Horusec-CLI. You rock 🚀

**Comment by trenerok** [comment]
Hi @wiliansilvazup ,
looks like issue was fixed ) Thank you !
