### ISSUE TITLE
null value in sonarqbue export json

### ISSUE THREAD

**Issue by td-miguel-lopes** [ZupIT/horusec#442]
Hi guys,

when scanning a test project I noticed that the Sonar export comes will a null value:
{
  "issues": null
} 

Is it possible to have a square bracket (such as "[]") instead of the null value as the Sonar import fails?

thanks,

Best regards
Miguel

**Comment by nathannascimentozup** [comment]
Hi @td-miguel-lopes! which CLI version are you using?

```
horusec version
```
