### ISSUE TITLE
API retorna analysisVulnerabilities: (severity: must be a valid value.).

### ISSUE THREAD

**Issue by econtessotto** [ZupIT/horusec#446]
**What happened**:
Implantamos o Horusec Web em uma infra Kubernetes usando Helm. Somos capazes de acessar o portal, criar workspace, repo, token, etc. Ao utilizar o Horusec-CLI com parâmetro para envio dos dados para API estamos recebendo o log:

time="2021-05-05T08:37:00-03:00" level=error msg="[HORUSEC] something went wrong while sending analysis to horusec. Check if your current version of Horusec-CLI is compatible with version in Horusec-API -> {\"code\":400,\"status\":\"Bad Request\",\"content\":\"analysisVulnerabilities: (severity: must be a valid value.).\"}\n"
time="2021-05-05T08:37:00-03:00" level=error msg="[HORUSEC] something went wrong while finding analysis to horusec -> {\"code\":404,\"status\":\"Not Found\",\"content\":\"{ERROR_REPOSITORY} database not found records\"}\n"

**How to reproduce it (as minimally and precisely as possible)**:
./horusec start -p "./" -u "https://horusec.nossodominio.com.br/api" -a "1bf64735-e1a1-48fb-812f-232b3e87ba52" --repository-name "teste"

**Anything else we need to know?**:
Estamos usando a última versão do Horusec Web disponível aqui no GitHub; o Horusec-CLI instalamos usando:
curl "https://horusec.io/bin/v1-10-3/win_x64/horusec.exe" -o "./horusec.exe"

**Environment**:
- Horusec version (use `horusec version`): Actual version installed of the horusec is: v1.10.3
- Operating System: Windows Pro 10

**Comment by nathannascimentozup** [comment]
Olá @econtessotto, tudo bem? Qual versão da imagem da API que está instalada no seu cluster?

**Comment by econtessotto** [comment]
Olá!!! Obrigado pelo retorno.
A versão é:

    Image:          horuszup/horusec-api:v2.8.0
    Image ID:       docker-pullable://horuszup/horusec-api@sha256:784f75607de5a7147817246ebd477d43b9fb03b3c05482414ace73f888a9e1f5

**Comment by nathannascimentozup** [comment]
A versão da CLI que você está utilizando e a versão da API não são compatíveis. Você pode atualizar a versão dos serviços dentro do seu cluster ou fazer um downgrade da CLI. 
Recomendamos que você atualize os serviços para poder utilizar a CLI na última versão com as regras de vulnerabilidades atualizadas.

**Comment by econtessotto** [comment]
Sucesso! Muito obrigado!!!
