### ISSUE TITLE
Add tool version # to JSON results file.

### ISSUE THREAD

**Issue by davewichers** [ZupIT/horusec#472]
It is sometimes useful to know the version of the tool used, when looking at the results file of a tool. Especially if you want to compare old/new results. Can you add the tool version as an attribute at the top of the .json results file generated by the tool?

**Comment by wiliansilvazup** [comment]
Thanks for the feedback @davewichers , the idea is awesome, let's add it to our backlog :)
Any changes we will update this issue!

**Comment by davewichers** [comment]
Do let me know when this is added. I'm not sure if you are aware of OWASP Benchmark (which is an OWASP project I run), but the project recently added scoring support for your tool: https://owasp.org/www-project-benchmark/#div-tool_support (under free SAST). The Horusec parser was actually written by @darkspirit510 (Sascha). I just merged it in.

**Comment by nathannascimentozup** [comment]
> Do let me know when this is added. I'm not sure if you are aware of OWASP Benchmark (which is an OWASP project I run), but the project recently added scoring support for your tool: https://owasp.org/www-project-benchmark/#div-tool_support (under free SAST). The Horusec parser was actually written by @darkspirit510 (Sascha). I just merged it in.

we are already working on it.
very nice to know that Horusec will be in the benchmark

**Comment by nathannascimentozup** [comment]
related #473

**Comment by wiliansilvazup** [comment]
Added on latest version of the horusec-cli: `v2.0.2`
tnks all 🚀
