### ISSUE TITLE
horusec will support dataflow？

### ISSUE THREAD

**Issue by k4n5ha0** [ZupIT/horusec#475]
hi，pls tell me，did horusec will support dataflow？i find some sec sast lib. but they don't support dataflow，and some of them dont‘t support  cross files  dataflow. 
thx

**Comment by wiliansilvazup** [comment]
hello @k4n5ha0, in the short term we can say no, as our goal now is to focus on the languages we already support ensuring a dependency analysis and a semantic analysis, but let's take note to leave it in our roadmap for a medium / long term implementation :)
