### ISSUE TITLE
A Trojan.Malware detected in release executable file.

### ISSUE THREAD

**Issue by ashim-k-saha** [ZupIT/horusec#484]
![image](https://user-images.githubusercontent.com/32305652/123140281-bac99500-d474-11eb-97b4-caf8e38ef938.png)

**Comment by wiliansilvazup** [comment]
hello @ashim-k-saha 

Tnks for your feedback 🚀 

Can you give us some more information?
* What program is identifying our binary as a trojan;
* Your operating system;
* Horusec-CLI version;
* Possible way we can reproduce this scenario.

**Comment by nathanmartinszup** [comment]
As we didn't have an answer, I'll close for now.
