### ISSUE TITLE
Horusec fails to start a scan

### ISSUE THREAD

**Issue by rthomas-sf** [ZupIT/horusec#490]
**What happened**:
I've been trying to use Horusec for static analysis of my code as part of integrating into my build cycle. I built a docker image for Horusec to be used as a Jenkins Agent, however the scan keeps failing. The command and response is mentioned below:

`horusec start -p=src/ -o=json -O=out/result.json -i=**/rpms/*,**/Conda/*,**/openssl/*,**/tomcat/containers/*/BUILDING.txt,**/tomcat/containers/*/LICENSE,**/tomcat/containers/*/NOTICE,**/tomcat/containers/*/README.md,**/tomcat/containers/*/RELEASE-NOTES,**/tomcat/containers/*/RUNNING.txt,**/tomcat/containers/*/bin/*,**/tomcat/containers/*/conf/*,**/tomcat/containers/*/lib/*,*.tar.gz,*.pyc -t=100000`

```
time="2021-07-14T11:51:31Z" level=warning msg="{HORUSEC_CLI} When starting the analysis WE SKIP A TOTAL OF 30451 FILES that are not considered to be analyzed. To see more details use flag --log-level=debug"
time="2021-07-14T11:53:49Z" level=error msg="{HORUSEC_CLI} Error when copy project to .horusec folder" error="open /var/jenkins_home/workspace/Devops/ProjectA/Security_Scan_Test/src/.horusec/5b9692bb-0a3f-434a-9a5f-c0a6c2c179e7/Sample_Project-extract/Sample_Project_V2/tomcat/containers/Application/lib/json.jar-extract/.project: no such file or directory"
17:24:29  Error: open /var/jenkins_home/workspace/Devops/ProjectA/Security_Scan_Test/src/.horusec/5b9692bb-0a3f-434a-9a5f-c0a6c2c179e7/Sample_Project-extract/Sample_Project_V2/tomcat/containers/Application/lib/json.jar-extract/.project: no such file or directory
```

**Anything else we need to know?**:
I'm running Horusec to scan my build artifacts, not source code. I first extract the artifacts and then provide them as input to  Horusec.

**Environment**:
- Horusec version: V2.2.1
- Operating System: Docker image with Ubuntu 20.04 as base image
- Network plugin / Tool and version (if this is a network-related / tool bug): -
- Others: -

**Comment by nathanmartinszup** [comment]
Hi, @rthomas-sf.

To run Horusec with docker it is necessary create a volume to the project  and let the docker.sock available.

Ex : `docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:latest horusec start -p /src -P $(pwd)`

We also have an official image to the cli: `horuszup/horusec-cli:latest`.

To know more about running the cli with docker, check out our docs:
* https://github.com/ZupIT/horusec#usage-with-docker
* https://horusec.io/docs/cli/installation/#installation-via-image-docker

About the artifacts, Horusec is a tool that make analysis of source code, not artifacts.

**Comment by rthomas-sf** [comment]
Hi @nathanmartinszup , thanks for the quick reply. Even after providing a volume to the image and access to docker.sock, the same problem persists. I'm seeing this for files of a specific type like .pyc, .rpm but as you already mentioned this may be because the tool was designed to run only on source code and not on compiled code like .pyc (my best guess). My temporary workaround was to delete the files with these extensions. This removed the error for me.
I'm building a custom image with a bunch of security scanning tools in it so that's why I didn't use the official image.

**Comment by nathanmartinszup** [comment]
@rthomas-sf. 

It shouldn't be returning an error. I will take a look at what's going on with this kind of extension.

I will be closing this issue, any further problem just re-open it. 

Thanks for the feedback!
