### ISSUE TITLE
Multiple workdirs for the same language only processes the last directory

### ISSUE THREAD

**Issue by wibisana-kargo** [ZupIT/horusec#497]
**What happened**:

When running horusec CLI with multiple workdirs for the same language, only the last directory is processed.

**What you expected to happen**:

Each folder should be processed separately, then the results should be aggregated into the report

**How to reproduce it (as minimally and precisely as possible)**:

- Run `horusec generate` to create a template config file
- Enable only `bandit` scanner (for simplicity sake)
- Add `app/views/api` and `app/views/sessions` **in order** to the python secition in `horusecCliWorkDir`
- Run `horusec start --config-file-path horusec-config.json --log-level debug > /dev/null`

After running this, 2 results stand out

- The last folder is shown multiple times when setting up the path to run the tool
- The scan finished without any vulnerabilities found (should be 4 in `api`, and 0 in `sessions`)

![image](https://user-images.githubusercontent.com/53174255/126973767-2242dcca-5b3e-4825-b9f7-ff44c8dbdbb5.png)

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`): v2.3.0
- Operating System: WSL 2 (Ubuntu 18.04.5 LTS)
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Sample repository: https://github.com/Contrast-Security-OSS/DjanGoat
- Sample configuration: https://gist.github.com/wibisana-kargo/0ced66b252683e3c748b12e062500bd6

**Comment by wibisana-kargo** [comment]
> **What happened**:
> 
> When running horusec CLI with multiple directories for the same language, only the last directory is processed.
> 
> **What you expected to happen**:
> 
> Each folder should be processed separately, then the results should be aggregated into the report
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> * Run `horusec generate` to create a template config file
> * Only enable `bandit` CLI tool (for simplicity sake)
> * Add `app/views/api` and `app/views/sessions` **in order** to the python secition in `horusecCliWorkDir`
> * Run `horusec start --config-file-path horusec-config.json --log-level debug > /dev/null`
> 
> After running this, 2 results stand out
> 
> * The last folder is shown multiple when setting up the path to run the tool
> * The scan finished without any vulnerabilities found (should be 8 in `api`, and 0 in `sessions`)
> 
> ![image](https://user-images.githubusercontent.com/53174255/126973767-2242dcca-5b3e-4825-b9f7-ff44c8dbdbb5.png)
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Horusec version (use `horusec version`): v2.3.0
> * Operating System: WSL 2 (Ubuntu 18.04.5 LTS)
> * Network plugin / Tool and version (if this is a network-related / tool bug):
> * Used repository: https://github.com/Contrast-Security-OSS/DjanGoat
> * Used configuration: https://gist.github.com/wibisana-kargo/0ced66b252683e3c748b12e062500bd6

**Comment by nathanmartinszup** [comment]
Fix merged! It will be avaliable on the next release.

Thanks for the contribution.
