### ISSUE TITLE
Include /tmp directory in analysis

### ISSUE THREAD

**Issue by subhash-CN** [ZupIT/horusec#499]
**What would you like to be added**:
add a command-line argument to include specific directories or allow to configure the default excluded directories.

**Why is this needed**:
I would like to analyze the /tmp directory in one of my projects.

**Comment by nathanmartinszup** [comment]
Hi @subhash-CN.

We are going to add this feature to the backlog and in the near future it should be released.

Thanks for your feedback!

**Comment by wiliansilvazup** [comment]
Hello @subhash-CN tnks for your feedback!

In next release this changes go enable for usage! 😄  🚀
