### ISSUE TITLE
Add PHP support

### ISSUE THREAD

**Issue by nathannascimentozup** [ZupIT/horusec#50]
Add horusec-cli PHP support, you can use following some of these instructions:
Using horusec-engine:
* https://github.com/ZupIT/horusec/blob/master/HOWTO.md#adding-new-tool-using-horusec-engine
Using existing tool:
* https://github.com/ZupIT/horusec/blob/master/HOWTO.md#adding-security-tool

Or integrate the existed option:

https://github.com/FloeDesignTechnologies/phpcs-security-audit

**Comment by wiliansilvazup** [comment]
Added on PR #177
