### ISSUE TITLE
How to add Checkov Tool to Scan Terraform

### ISSUE THREAD

**Issue by danang-kargo** [ZupIT/horusec#507]
**What happened**:

TfSec is good for scan terraform code but this tool needs to do `terraform init` first. Run in locally yes we can do that, but if we integrate Horusec on the CI/CD it's hard to do that. So, I look another tool like Checkov (https://github.com/bridgecrewio/checkov) which can scan terraform without `terraform init`. But, when I check into this directory https://github.com/ZupIT/horusec/tree/main/internal/services/formatters/hcl the folder structure is not designed to have multiple tools as mentioned on the docs https://horusec.io/docs/tutorials/how-to-add-tools-using-horusec-engine

Any suggestions?

**Comment by wiliansilvazup** [comment]
This is really a problem, this tool is outside the project's architectural standards.

To solve and if you want to contribute to the project :D

You can move files and folders:
* horusec/internal/services/formatters/hcl/entities/*
* horusec/internal/services/formatters/hcl/config.go
* horusec/internal/services/formatters/hcl/config.go
* horusec/internal/services/formatters/hcl/formatter.go
* horusec/internal/services/formatters/hcl/formatter_test.go

Inside the folder:
* horusec/internal/services/formatters/hcl/tfsec/...

And you can work on the new analysis tool at:
* horusec/internal/services/formatters/hcl/checkov/...

Then just update the [Dockerfile](https://github.com/ZupIT/horusec/blob/main/internal/services/formatters/hcl/deployments/Dockerfile) to contain both tools :)

**Comment by wiliansilvazup** [comment]
For test local image or image from private repository you can usage `horusecCliCustomImages` in your [configuration file](https://horusec.io/docs/cli/resources/#3-flags).

**Comment by wibisana-kargo** [comment]
Hi, I'm currently trying to implement a new analyzer for HCL (Checkov).

Looking through the existing code, it seems like I have to update the `horusec-devkit` repo as well to add Checkov to the tool enums. Is this correct or am I misunderstanding this somehow?

**Comment by wiliansilvazup** [comment]
Yes, is this correct.

In horusec documentation you can found an tutorial - [How to add a new security tool to Horusec?](https://horusec.io/docs/tutorials/how-to-add-security-tools-to-horusec/) for help in this step

**Comment by wibisana-kargo** [comment]
Thanks for the answer

**Comment by danang-kargo** [comment]
Wow, nice catch @wibisana-kargo, Bump on this!  Would love to see Horusec perform terraform code scanning in CI/CD.

Hi @wiliansilvazup, is that pull request ready for review?

**Comment by wiliansilvazup** [comment]
@danang-kargo @wibisana-kargo 

Pull request approved and merged in main branch 

New feature enable in horusec-cli version : `v2.4.1` 

Tnks for contribution 🚀
