### ISSUE TITLE
Error on run analysis in horusec examples folder

### ISSUE THREAD

**Issue by wiliansilvazup** [ZupIT/horusec#518]
**What happened**:
When clone horusec project and run analysis inside examples folder in final logs return an error.

**What you expected to happen**:
not return error

**How to reproduce it (as minimally and precisely as possible)**:
* Install horusec latest version v2.4.1
* `git clone https://github.com/ZupIT/horusec.git`
* `cd horusec/examples`
* `horusec start -p . --log-level=trace`

**Anything else we need to know?**:
I'll upload log file but inside her not show the error.
[horusec-log-2021-08-10 08:15:25.log](https://github.com/ZupIT/horusec/files/6961272/horusec-log-2021-08-10.08.15.25.log).

In this print show error in terminal
![image](https://user-images.githubusercontent.com/63816070/128859376-44005d3e-37b1-4b70-a0cb-c23a1d283b04.png)

**Environment**:
- Horusec version (use `horusec version`): v2.4.1
- Operating System: Linux Ubuntu 20.04

**Comment by matheusalcantarazup** [comment]
I think that the problems is [here](https://github.com/ZupIT/horusec/blob/main/internal/controllers/printresults/print_results.go#L381)
We are passing a wrong path to write the output.
