### ISSUE TITLE
How to configure rules for internal tools ?

### ISSUE THREAD

**Issue by cactuschibre** [ZupIT/horusec#532]
Hello,

I want to customize the rules for Semgrep and Gitleaks.
I cannot find the documentation about this in the Horusec documentation.

Can anyone help me to do that ? 

Thanks :)

**Comment by wiliansilvazup** [comment]
Hello @cactuschibre 

Rules customize for others tools is not possible

Only tools using Horusec-Engine is possible customized:
See [this tutorial](https://horusec.io/docs/tutorials/how-to-adding-custom-rules/)

**Comment by cactuschibre** [comment]
Oh no, too bad ...
The configurations are in all `config.go`, right ?
Like `internal/services/formatters/leaks/gitleaks/config.go` for Gitleaks.
So, only "hard" modification of these files and redployment could permit to change the configuration in place ?

If I knew more Golang, I could get more involved in this good project ...

**Comment by wiliansilvazup** [comment]
hahaha' don't worry golang is super intuitive and the horusec project too 😄 

well, let's start by changing the gitleaks config file:
When gitleaks performs the build its docker image is [located here](https://github.com/ZupIT/horusec/blob/main/internal/services/formatters/leaks/deployments/Dockerfile), and semgrep is [located here](https://github.com/ZupIT/horusec/blob/main/internal/services/formatters/generic/deployments/Dockerfile).

When it's necessary to perform local tests you need to locally build your tool in docker image is necessary switch using the `[horusecCliCustomImages](https://horusec.io/docs/cli/resources/#1-configuration-file)` setting to point to your locally created image.

And don't worry if in your pull request we identify that the image has changed we will officially update it on our dockerhub as well.

**Comment by wiliansilvazup** [comment]
i'll close this issue for now, any update you can reopen again, tnks 🚀
