### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [ZupIT/horusec#56]
**What would you like to be added**:

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

**Why is this needed**:

TOC is very useful to hop between the docs/info of the readme and avoids useless scrolling.

@nathanmartinszup / @wiliansilvazup do assign this issue to me after approval :)

**Comment by nathannascimentozup** [comment]
It's a good point. we'll be very grateful if you can contribute by solving this issue. @ng29

**Comment by ng29** [comment]
> > It's a good point. we'll be very grateful if you can contribute by solving this issue. @ng29
> 
> Sure @nathannascimentozup , will raise PR today only for above issue. 👍

Voila, toc IS READY @nathannascimentozup , please review and merge 👍

**Comment by wiliansilvazup** [comment]
Tnks for you contributing :smile: 
Fixed on PR #57
