### ISSUE TITLE
How to pass arguments to the Bandit tool?

### ISSUE THREAD

**Issue by afonsofilhozup** [ZupIT/horusec#578]
**What happened**:
When testing in Python, the word `assert` is used, the tool [Bandit](https://bandit.readthedocs.io/en/latest/) recognizes this as unnecessary, as exemplified below:
```
Language: Python
Severity: LOW
Line: xx
Column: xx
SecurityTool: Bandit
Confidence: HIGH
File: /path/to/file.py
Code: 3 def test_sample():
4     assert 1 == 1

Details: Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
Type: Vulnerability
ReferenceHash: xxxxxxxxxxxxxxxxxxxxxx
```
To get around this, the Bandit tool is informed of the [files to be ignored](https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html), but how to do this through Horusec?

**How to reproduce it**:
1. Create a file with this content:
```python
def test_sample():
    assert 1 == 1
```
2. Run `horusec start -p="./" -e="true"`.

**Environment**:
- Horusec version: v2.5.0 / dist normal
- Operating System: Ubuntu 20.04

**Comment by wiliansilvazup** [comment]
Hello @afonsofilhozup

you can ignore using two flags:

- In follow example this command  run horusec and ignore all files with prefix **_test.py** and all folder with name **mocks**
```
horusec start -p . -e true --ignore="**/*_test.py, **/mocks/**"
```

- And other example you can setup the vulnerability found as a false positive see follow example
```
horusec start -p . -e true --false-positive="HASH1, HASH2"
```

both proposals can be used through all Horusec usage options such as flags, environment variables, configuration file, see more in [our documentation](https://horusec.io/docs/cli/resources/#start)

**Comment by afonsofilhozup** [comment]
But this option will skip all tests on test files? This Bandit option ignores only the use of the `assert` word, the other Bandit validations are still performed.
