### ISSUE TITLE
Git author command failing on windows

### ISSUE THREAD

**Issue by ckruppe** [ZupIT/horusec#581]
**What happened**:
Git command for author check failes with: "level=error msg="{HORUSEC_CLI} Error when execute commit author command: " error="exit status 128" line_and_path="-L 13,13:***"
(FilePath is obfuscated but correct)

**What you expected to happen**:
Git command should not fail.

**How to reproduce it (as minimally and precisely as possible)**:
Run with horusecCliEnableCommitAuthor enabled on windows.

**Anything else we need to know?**:
Looked into this a bit and it seems for windows the format parameter is false.
In code: git log -1 --format={%n  ^^^^^author^^^^^:^^^^^%an^^^^^, %n ^^^^^email^^^^^:^^^^^%ae^^^^^, %n ^^^^^message^^^^^:^^^^^%s^^^^^, %n ^^^^^date^^^^^:^^^^^%ci^^^^^, %n ^^^^^commitHash^^^^^:^^^^^%H^^^^^%n }

Working command under windows is:
git log -1 --format="{%n  ^^^^^author^^^^^:^^^^^%an^^^^^, %n ^^^^^email^^^^^:^^^^^%ae^^^^^, %n ^^^^^message^^^^^:^^^^^%s^^^^^, %n ^^^^^date^^^^^:^^^^^%ci^^^^^, %n ^^^^^commitHash^^^^^:^^^^^%H^^^^^%n }"

**Environment**:
- Horusec version (use `horusec version`): v1.10.3
- Operating System: Windows 10
- Network plugin / Tool and version (if this is a network-related / tool bug): git version 2.18.0.windows.1

**Comment by wiliansilvazup** [comment]
Hello @ckruppe i open o PR #584 for fix this issue 😄  

tnks for you contribuition, you rock 🚀

**Comment by ckruppe** [comment]
Thx for the fast respone :)

**Comment by matheusalcantarazup** [comment]
Closing this issue since the PR already merged on main branch.
