### ISSUE TITLE
Horusec scan does not identify *.jsx files as JavaScript.

### ISSUE THREAD

**Issue by ckruppe** [ZupIT/horusec#583]
Horusec scan does not identify *.jsx files as JavaScript.

**What happened**:
Scanned my project and can't send results to API. Because of this error:
{\"code\":400,\"status\":\"Bad Request\",\"content\":\"analysisVulnerabilities: (language: must be a valid value.).\"}

The report that generates this error is this:
Language: Unknown
Severity: MEDIUM
Line: 110
Column: 22
SecurityTool: Semgrep
Confidence:
File: ***/src/modules/Faq.jsx

Details: Setting HTML from code is risky because it’s easy to inadvertently expose your users to a cross-site scripting (XSS) attack.
Type: Vulnerability

So horusec seams not to recognize jsx files ans Javascript. Thus the API will not accept it.

**What you expected to happen**:
I expect that the found language for *.jsx files is JavaScript and that the API accepts also Unknown languages.

**How to reproduce it (as minimally and precisely as possible)**:
Scan an .jsx file with an vulnerability.

**Environment**:
- Horusec version (use `horusec version`): v1.10.3
- Operating System: Windows 10

Here the full log of the github action:

Run curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
Download version: latest
Installing Horusec for Linux x64
Downloading horusec...
https://github.com/ZupIT/horusec/releases/latest/download/horusec_linux_x64
Horusec was downloaded and moved to /usr/local/bin/horusec
Actual version installed of the horusec is: v2.5.0
dist: normal
time="2021-09-15T12:50:28Z" level=info msg="Set log file to /home/runner/work/o2-glasfaser/o2-glasfaser/tmp/horusec/horusec-log-2021-09-15 12:50:28.log"

time="2021-09-15T12:50:28Z" level=warning msg="{HORUSEC_CLI} When starting the analysis WE SKIP A TOTAL OF 60 FILES that are not considered to be analyzed. To see more details use flag --log-level=debug"

time="2021-09-15T12:50:28Z" level=warning msg="{HORUSEC_CLI} PLEASE DON'T REMOVE \".horusec\" FOLDER BEFORE THE ANALYSIS FINISH! Don’t worry, we’ll remove it after the analysis ends automatically! Project sent to folder in location: [/home/runner/work/*****/.horusec/541d930f-dcd9-4a84-98ff-b243f7043bbf]"

time="2021-09-15T12:50:28Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 600s"
time="2021-09-15T12:50:28Z" level=warning msg="{HORUSEC_CLI} Starting the analysis with git history enabled. ATTENTION the waiting time can be longer when this option is enabled!"
time="2021-09-15T12:50:43Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 585s"
time="2021-09-15T12:50:58Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 570s"
time="2021-09-15T12:51:13Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 555s"
time="2021-09-15T12:51:28Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 540s"
time="2021-09-15T12:51:43Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 525s"
time="2021-09-15T12:51:58Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 510s"
time="2021-09-15T12:52:13Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 495s"
time="2021-09-15T12:52:28Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 480s"
time="2021-09-15T12:52:43Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 465s"
time="2021-09-15T12:52:58Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 450s"
time="2021-09-15T12:53:13Z" level=info msg="Hold on! Horusec is still analyzing your code. Timeout in: 435s"

time="2021-09-15T12:53:15Z" level=error msg="[HORUSEC] something went wrong while sending analysis to horusec. Check if your current version of Horusec-CLI is compatible with version in Horusec-API -> {\"code\":400,\"status\":\"Bad Request\",\"content\":\"analysisVulnerabilities: (language: must be a valid value.).\"}\n"
time="2021-09-15T12:53:15Z" level=error msg="{ERROR_HTTP} request returned a error status code" error= status="Not Found" statusCode=404
time="2021-09-15T12:53:15Z" level=error msg="[HORUSEC] something went wrong while finding analysis to horusec -> {\"code\":404,\"status\":\"Not Found\",\"content\":\"{ERROR_DATABASE} database not found records\"}\n"

==================================================================================

HORUSEC ENDED THE ANALYSIS WITH STATUS OF "error" AND WITH THE FOLLOWING RESULTS:

==================================================================================

Analysis StartedAt: 2021-09-15 12:50:28
Analysis FinishedAt: 2021-09-15 12:53:14

==================================================================================

Language: Unknown
Severity: MEDIUM
Line: 110
Column: 21
SecurityTool: Semgrep
Confidence: LOW
File: /home/runner/work/*****/src/modules/Faq.jsx
Code:                     <script
                        // eslint-disable-next-line react/no-danger
    
Details: Setting HTML from code is risky because it’s easy to inadvertently expose your users to a cross-site scripting (XSS) attack.
Type: Vulnerability

==================================================================================

Language: JavaScript
Severity: MEDIUM
Line: 110
Column: 21
SecurityTool: Semgrep
Confidence: LOW
File: /home/runner/work/*****/pages/_app.js
Code:                     <script
                        async
                        // eslint-disable-
Details: Setting HTML from code is risky because it’s easy to inadvertently expose your users to a cross-site scripting (XSS) attack.
Type: Vulnerability

==================================================================================

In this analysis, a total of 2 possible vulnerabilities were found and we classified them into:
Total of Vulnerability MEDIUM is: 2

==================================================================================

time="2021-09-15T12:53:15Z" level=warning msg="[HORUSEC] 2 VULNERABILITIES WERE FOUND IN YOUR CODE SENT TO HORUSEC, TO SEE MORE DETAILS USE THE LOG LEVEL AS DEBUG AND TRY AGAIN"

==================================================================================

time="2021-09-15T12:53:15Z" level=warning msg="{HORUSEC_CLI} During execution we found some problems:"

time="2021-09-15T12:53:15Z" level=warning msg="{HORUSEC_CLI} Error It looks like your project doesn't have a package-lock.json file. If you use NPM to handle your dependencies, it would be a good idea to commit it so horusec can check for vulnerabilities"
time="2021-09-15T12:53:15Z" level=warning msg=" {HORUSEC_CLI} Error It looks like your project doesn't have a yarn.lock file. If you use Yarn to handle your dependencies, it would be a good idea to commit it so horusec can check for vulnerabilities"

**Comment by wiliansilvazup** [comment]
hello @ckruppe 

you can pass version of service horusec-api and check if horusec-cli is version is really v1.10.3 ?

**Comment by ckruppe** [comment]
How do i find the api version? But both is today freshly installed and downloaded. :)

**Comment by ckruppe** [comment]
Ok found it: horuszup/horusec-api:v2.16.8
And the cli version is v1.10.3 on lokal and on github actions i have the same problem. There i use the snipped you provided in your dokumentation

**Comment by wiliansilvazup** [comment]
ok, tnks for informations!

for now horusec in v2 support CLI v1, this error will be correct comming son.

but the recommended is you usage latest version of Horusec-CLI `v.2.5.0` you can found how install [here](https://horusec.io/docs/cli/installation/#local-installation) and if you used horusec-api and other service in v1 we have an [tutorial](https://horusec.io/docs/migrate-v1-to-v2/) for you migrate your data.

**Comment by ckruppe** [comment]
Thx for the detailed information.
I checked again and in github actions we use the cli v2.5.0 already. Locally i used the v1.10.3 but both give me the same error.
The docker-compose we used from your horusec-platform repo uses already the v2.16.8 for every service.

Unfortunately the error remains. :(

**Comment by ckruppe** [comment]
Edited the issue with the actual ci log.

**Comment by ckruppe** [comment]
Just for information: Today i scanned another project of ours and in this project jsx files get identified as JavaScript. I'm not sure thats causing this.
