### ISSUE TITLE
dangerouslySetInnerHTML react rule seems to have no language associated

### ISSUE THREAD

**Issue by ckruppe** [ZupIT/horusec#588]
**What happened**:
If an .jsx file contains the dangerouslySetInnerHTML prop it gets reported by semgrep but with language "Unknown"
This causes problems in reporting because the horusec api does not accept "Unknown" as language value.

**What you expected to happen**:
I expected to have the error reportet as language "JavaScript" and the horusec api accepting the report.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce this, scan following code in an .jsx file:
```Javascript
const TestComponent = ({html}) => (
    <div
        dangerouslySetInnerHTML={{__html: html}}
        otherPropToShowCaseRightLanguage={() => window.addEventListener('resize', () => {})}
    />
)
```

**Anything else we need to know?**:
The second prop is there to showcase that other errors get reportet as "JavaScript"

**Environment**:
- Horusec version (use `horusec version`): v2.5.0
- Operating System: Windows 10, Ubuntu 20.04.3
- Network plugin / Tool and version (if this is a network-related / tool bug): Semgrep seems to be v0.63.0
- Others: Horusec-Api v2.16.8

**Comment by nathanmartinszup** [comment]
Hi, @ckruppe.

Our team is already checking what happened.

Thanks for the feedback!

**Comment by nathanmartinszup** [comment]
Hello @ckruppe.

The problem was fixed and will be avaliable in the next release of the CLI and Platform.

Thanks again for the feedback!
