### ISSUE TITLE
Create a Unit Test mechanism for each vulnerability

### ISSUE THREAD

**Issue by otaviojava** [ZupIT/horusec#597]
Currently, we have an integration test that allows us to run a test. However, we don't have a unit test for all vulnerabilities types.

It will be amazing if we create an engine to test each vulnerability.
This engine would have two verifications:

* One to make sure that the engine find the code vulnerability
* One to avoid false-positive test

Once we have this motor, it would be great to receive tests from the community.

**Comment by wiliansilvazup** [comment]
for tools created using horusec-engine we have only unit tests for [leaks](https://github.com/ZupIT/horusec/blob/main/internal/services/engines/leaks/regular/regular_test.go). it's good first issue for resolve in horusec improvements of others tools 😄

**Comment by mcruzdev** [comment]
Hi @otaviojava,
Can you assign it for me?

**Comment by otaviojava** [comment]
Hey @mcruzdev how are you?
I believe that @wiliansilvazup  is working on it.
Will, could you sync up?

**Comment by matheusalcantarazup** [comment]
Hi @mcruzdev , thanks for you interest on contributing for Horusec. We created a new issue #630  with all tests that we should create and some guide to help to create them.

**Comment by matheusalcantarazup** [comment]
I'm closing this issue since we created a new one on #630 with all the tasks that should be done.
