### ISSUE TITLE
Horusec is not reading my config-file.json

### ISSUE THREAD

**Issue by NahuelHerr** [ZupIT/horusec#656]
**What happened**: I am running Horusec in a pipeline using Docker. I have a Python script that receives the desired parameters and configurations, runs the scan, and shows the results. Two weeks ago it was working fine, but I ran it again yesterday and some issues appeared. First, it returned an error saying "open: /tmp is a directory". I just create a new branch and without any change in the code, the scanner started to work but currently, it is not taking my config-file.json

**How to reproduce it (as minimally and precisely as possible)**: This is how I am building the command structure in my Python code:  
```
def GetStartHorusecCMD(imageName, reportName, outputFormat, configFilePath):  
    command =("docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src "+imageName+
            ":latest horusec start -p /src -P $(pwd) --config-file-path "+configFilePath+" -o "+outputFormat)  
    if outputFormat != 'text':
            command = command + " -O /src/Horusec/"+ reportName
   return command 
```
And the variables that I am passing in my pipeline (running in an Ubuntu environment in GitHub) are:
```
imageName: "horuszup/horusec-cli" 
reportName: "Horusec-21-10-07"
outputFormat: 'json'
configFilePath: '/src/Horusec/horusec-config.json'
```

**Anything else we need to know?**: This is my project structure:
![image](https://user-images.githubusercontent.com/88396520/136397385-87ef754d-cc09-4eb3-adec-9d0d768f4969.png)

Configurations showed using the --log-level=debug flag:
![image](https://user-images.githubusercontent.com/88396520/136398762-d475a832-abe2-4912-a3a4-83ac8a34d6d9.png)

**Environment**:
- Horusec version (use `horusec version`): We are downloading the latest version from Docker
- Operating System: Ubuntu-latest (GitHub pipeline environment)
- Network plugin / Tool and version (if this is a network-related / tool bug): N/A
- Others:

**Comment by lucasbrunozup** [comment]
Hello @NahuelHerr 
Apparently your command is correct.
We will be analyzing to identify the possible reason and I will get back to you soon.

tnks for you report  :rocket:

**Comment by NahuelHerr** [comment]
Hello, 
today is tried again and I still having the same behaviour.
First I tried to set a custom config file path, but I receive this error message:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:latest horusec start -p /src -P $(pwd) --config-file-path /src/Horusec/horusec-config.json -o json -O /src/Horusec/Horusec-16-20211015115537.json
Error: open /tmp: is a directory
```
Later, I moved the horusec-config.json to the root and the scanner did not read it. Below I add some images to show you my project:
Command with the folder structure:
![image](https://user-images.githubusercontent.com/88396520/137487171-8dff1fea-087d-4806-a39e-17c175979fe6.png)

How I call the HorusecScan.py script. This script run the scan (in this image you can see a CONFIG_FILE_PATH variable, but I did not use it in the script for this try)
![image](https://user-images.githubusercontent.com/88396520/137487615-9e379df8-1af8-4ef8-9b52-3d47b732c59b.png)

**Comment by NahuelHerr** [comment]
These are the History and the Manifest of the image:
```
Pulled image history: 
IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
25f7cc6fa4d4   6 days ago    /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      6 days ago    /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      6 days ago    /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      6 days ago    /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      6 days ago    /bin/sh -c #(nop)  CMD ["sh"]                   0B        
<missing>      6 days ago    /bin/sh -c chmod +x /usr/local/bin/horusec      0B        
<missing>      6 days ago    /bin/sh -c #(nop) COPY file:9853eeb88a12f634…   27.7MB    
<missing>      6 days ago    /bin/sh -c apk add git                          15.2MB    
<missing>      6 weeks ago   /bin/sh -c #(nop)  CMD ["sh"]                   0B        
<missing>      6 weeks ago   /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B        
<missing>      6 weeks ago   /bin/sh -c mkdir /certs /certs/client && chm…   0B        
<missing>      6 weeks ago   /bin/sh -c #(nop)  ENV DOCKER_TLS_CERTDIR=/c…   0B        
<missing>      6 weeks ago   /bin/sh -c #(nop) COPY file:5b18768029dab817…   1.85kB    
<missing>      6 weeks ago   /bin/sh -c #(nop) COPY file:abb137d24130e7fa…   587B      
<missing>      6 weeks ago   /bin/sh -c set -eux;   apkArch="$(apk --prin…   203MB     
<missing>      6 weeks ago   /bin/sh -c #(nop)  ENV DOCKER_VERSION=20.10.8   0B        
<missing>      6 weeks ago   /bin/sh -c [ ! -e /etc/nsswitch.conf ] && ec…   17B       
<missing>      6 weeks ago   /bin/sh -c apk add --no-cache   ca-certifica…   4.81MB    
<missing>      6 weeks ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      6 weeks ago   /bin/sh -c #(nop) ADD file:aad4290d27580cc1a…   5.59MB    


Docker Hub manifest: 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 5965,
      "digest": "sha256:25f7cc6fa4d475b8c47baa69dfa94e12524c2c12b9f62187a30390e8eac13a98"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2814446,
         "digest": "sha256:a0d0a0d46f8b52473982a3c466318f479767577551a53ffc9074c9fa7035982e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1935099,
         "digest": "sha256:14df950e5a796f46eb6615169002a1c428bd908141de49fb35ec026c206e77aa"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 154,
         "digest": "sha256:86a31cc9e913427e8959328b7d290bdcc639a9f84c11956c33c0ce112788cf19"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 61283898,
         "digest": "sha256:f7a4137012260e097fc6b4bf6d75ba3b193acb399fb1276687303dea63ba519c"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 544,
         "digest": "sha256:53d92eaf14165f5a5883286b050c77b9c7022efbde954c3b7e96e92565515f0a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1018,
         "digest": "sha256:e701314a31132c239baf0de9d4922559fc419c445e13c9ce7ffd8b4518b4f98e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 150,
         "digest": "sha256:5bea1be2ff281d99199cd048ef3bf1464615aec1ca9abfc20e73838913432dc0"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 8781498,
         "digest": "sha256:422f08ef0f6f67fcbd20597827d3f3375edb785cebd724a931fb7c0c383d66c1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 11203594,
         "digest": "sha256:7c540caa425da99de7975be1006840038e33a5f5b8ed715b9394ef0298dda777"
      }
   ]
}
```

**Comment by matheusalcantarazup** [comment]
After the error message, there is a stack trace or the usage from cli is showed?

**Comment by NahuelHerr** [comment]
1. In the report I can see that is using version v2.6.2
![image](https://user-images.githubusercontent.com/88396520/137495857-21aa7d48-2edd-4b4c-abaf-9bfd3993b0f9.png)

2. After the error message there is any stack trace as you can see:
![image](https://user-images.githubusercontent.com/88396520/137495994-f26b76e8-af4b-45f4-a063-8ba1784ea951.png)

I don't know if it can help, but I run the command this way. The GetStartHorusecCMD function is the one that I showed you [here](https://github.com/ZupIT/horusec/issues/656#issuecomment-944263414)
![image](https://user-images.githubusercontent.com/88396520/137496116-4e75d0c0-5e4b-46cb-be52-f4b47f5e837e.png)

**Comment by matheusalcantarazup** [comment]
I'm a bit confused now. How the output file was generated if there is an error?  On the message above you show a Github workflow configuration, the error does it occur in it? These error showed on last message (2) occurs on Windows or Linux?

**Comment by NahuelHerr** [comment]
Sorry, my bad. I did not tell you that I show you images of two different runs.
The scanner analyzes the code successfully if I do not include the **--config-file-path** option in the command. But, it does not read the  horusec-config.json file from the root. (In this [comment](https://github.com/ZupIT/horusec/issues/656#issuecomment-944263414) I show where I put the file). That is why I can see the version in a report.

The error related to the **/tmp** directory occurs when I add the **--config-file-path** option to the command. When I do this the execution fails and any report is generated.

The REPORT_NAME env is empty because it will be generated dynamically in the previous step of the pipeline called **Run GenerateReportName script**. As you can see in this image where I am showing to you the **Run Python script** step, the REPORT_NAME has a value, I set the **--config-file-path** option, and the error occurred
![image](https://user-images.githubusercontent.com/88396520/137500827-f1d06380-bbc2-44f5-87a6-1271a20db36c.png)

If I do not include the **--config-file-path** to the command the scanner works, but it did not read the  horusec-config.json file from the root:
![image](https://user-images.githubusercontent.com/88396520/137501339-c76f04ad-1fbb-48fb-9a4d-b55ae9f84fe5.png)

**Comment by NahuelHerr** [comment]
I have two different behaviors:
1. Using the **--config-file-path** option: when I use this option I move the config.json to the Horusec folder because there is where I want this file. When I do this I receive the error related to the /tmp directory.
2. Without the **--config-file-path** option: I leave the config.json in the root. I do not receive any error, but Horusec is not reading my config.json. 

I tried  with the **--log-file-path** as you said and I got the same error message
![image](https://user-images.githubusercontent.com/88396520/137931429-3e2d50b3-800e-465e-b2d0-bda9368136a5.png)

**Comment by matheusalcantarazup** [comment]
> If changing the path continue generating an error, can you try install the cli on workflow using the [docs](https://horusec.io/docs/cli/installation/#github-actions)? Just to check if the problem is with the binary ou running inside Docker.

Did you try this?

**Comment by matheusalcantarazup** [comment]
This is great!! 
I'm still confusing why this error is happening. [Here](https://github.com/ZupIT/horusec/blob/main/config/config.go#L144) is where we set the default log file path, I don't understand why in this scenario only `os.TempDir()` is used. But I think that its better to not fail the analysis if we get error on creating the log file anyway. I'will open a new issue to discover this bug.

Thank you very much for your help and patience, we really appreciate it.

We will release this patch very soon, on the next days.
