### ISSUE TITLE
Test Leaks engine rules

### ISSUE THREAD

**Issue by wiliansilvazup** [ZupIT/horusec#7]
**What would you like to be added**:

Create tests for Leaks analyse rules
https://github.com/ZupIT/horusec/blob/master/development-kit/pkg/engines/leaks/rules/rules_test.go

**Comment by fguisso** [comment]
hey guys, I'll try to get this one, you need each func in this file being validate? https://github.com/ZupIT/horusec/blob/e632fe0c4293cdd722f9c9097fa842247b1688ad/development-kit/pkg/enums/engine/advisories/leaks/regular/regular.go

**Comment by nathanmartinszup** [comment]
Hi @fguisso   !
The idea is to do a unit test for each function, passing a piece of vulnerable code that must be detected by the regex.
It is not necessary that all are tested, feel free to do what you feel comfortable with. Even one is of great help.
Thanks for your interest!

**Comment by wiliansilvazup** [comment]
Added on PR #158
