### ISSUE TITLE
docker: use docker client to validate requirements

### ISSUE THREAD

**Issue by matheusalcantarazup** [ZupIT/horusec#757]
**What would you like to be added**:
[When we validate the docker requirements](https://github.com/ZupIT/horusec/blob/main/internal/controllers/requirements/docker/docker.go#L42) we use `exec.Command` to execute docker commands and check if docker is running and if it's on minimum version required. Although it works well, a better approach would be to use the client from [`NewDockerClient`](https://github.com/ZupIT/horusec/blob/main/internal/services/docker/client/docker_config.go#L24) and use the method [`Ping`](https://pkg.go.dev/github.com/docker/docker/client#Client.Ping) to check version and verify if the daemon is running.

**Why is this needed**:
Since we are using different approaches to execute docker commands, we can have inconsistency when running them.  Before  #756 get merged when we set the `DOCKER_HOST` env the requirements execute successfully (the docker cli read env correctly)  but when we start the containers we get errors because we was using an client without reading the environment variables.

**Comment by luiguip** [comment]
I managed to get the version with the dockerClient.ServerVersion. How the error log of the function execDockerVersion from the file docker.go has to be formatted?
The exec.Command returns the response bytes when occurs an error.
The dockerClient.ServerVersion returns an empty types.Version struct.
The errors.New expects a string.

**Comment by matheusalcantarazup** [comment]
[SemverVersion]https://pkg.go.dev/github.com/docker/docker/client#Client.ServerVersion) return an error, you can use this error.
