### ISSUE TITLE
JavaScript evaluation not being warned

### ISSUE THREAD

**Issue by guilhermepaulozup** [ZupIT/horusec#765]
Using **horusec** to validate a ReactApp which uses JavaScript .eval() function in a component pass with no warnings.

Using this function:
```javascript
    const handleSubmit = () => {
      eval(data.document + data.digit)
    };
```
Should warn the user for the problem with *.eval()*.

**What would you like to be added**:
A Vulnerability warning about the .eval use.

**Why is this needed**:

Eval is not recommended since it can be used in attacks like:
https://owasp.org/Top10/pt_BR/A03_2021-Injection/

**Comment by lucasbrunozup** [comment]
Hello @guilhermepaulozup 

We have coverage for the `eval()` function, through the [HS-JAVASCRIPT-2](https://github.com/ZupIT/horusec/blob/main/internal/services/engines/nodejs/rules.go#L42) rule .

However, your scenario really wasn't caught by our rule, we will look for a way to improve it.

Feel free to suggest an improvement for it or even open a pull request.

**Comment by lucasbrunozup** [comment]
Hello @guilhermepaulozup 
The rule was to improve and will be available in the next release.

**Comment by guilhermepaulozup** [comment]
Thank you Lucas!
I'll be sure to checkout then.
