### ISSUE TITLE
Mainlines 

### ISSUE THREAD

**Issue by djashan** [ZupIT/horusec#787]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`):
- Operating System:
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by matheusalcantarazup** [comment]
Hi @djashan  can you please describe the issue?
