### ISSUE TITLE
Error on read horusec config with docker image

### ISSUE THREAD

**Issue by wiliansilvazup** [ZupIT/horusec#831]
Horusec not read my config-file

**What happened**:
I have this code:
```
package main

import "fmt"

func main() {
	printPwd()
	connectWitDatabase()
}

func printPwd() {
	password := "password"

	print("This is an password" + password)
}

func connectWitDatabase() {
	URI := fmt.Sprint("postgresql://root:root@postgresql:5432/horusecDB?sslmode=disable")
	print(URI)
}
```

and i run horusec with docker image:
`docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:v2.6.4 horusec start -p /src -P $(pwd)`

and i set two false positives in my horusec-config.json
```
{
  "horusecCliFalsePositiveHashes": [
    "6c869ddaa9a05faa9ce1ff9e8fd640920f17bf3e8ca8c3624e809972230daf9d",
    "50e0d77afb2bdd4d64861678315b1b075112a492fbc162f828edf2140e5fb065"
  ],
}
```
but this not work return all with type vulnerability

**What you expected to happen**:
return with type false positive

**Anything else we need to know?**:
output of the analysis [finished these log](https://github.com/ZupIT/horusec/files/7627217/horusec.log) in debug mode.
And i see this log from terminal `time="2021-11-30T16:27:32Z" level=warning msg="{HORUSEC_CLI} Config file not found"` not was write inside of the file.

**Environment**:
- Horusec version (use `horusec version`): 2.6.4
- Operating System: ubuntu 20.04
- Others: via docker image

**Comment by matheusalcantarazup** [comment]
The workdir of docker image is `/`, so the analysis will be based on `/` and the config file will be searched on `/` and since the volume here is mounted on `/src` the horusec could not find the default config file path (which is `/horusec-config.json`). So I think that the right command here should be:
```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v (pwd):/src horuszup/horusec-cli:alpha horusec start -p /src -P (pwd) --config-file-path /src/horusec-config.json
```

**Comment by wiliansilvazup** [comment]
this works, thks :)
