### ISSUE TITLE
Hash comparison for SecurityTool Nancy, between versions 2.6.9 and 2.7.0-rc.2

### ISSUE THREAD

**Issue by oliveirafelipezup** [ZupIT/horusec#938]
**What happened**:
When running the analysis on versions 2.6.9 and 2.7.0-rc.2 on example/go/example1, the same vulnerability that was displayed for the Nancy securityTool, hashes divergence

**What you expected to happen**:
That the hashes are the same regardless of the version used for analysis

**How to reproduce it (as minimally and precisely as possible)**:
Run an analysis on the examples/go/example1 directory with the versions mentioned in this issue

**Environment**:
- Horusec version (use `horusec version`): 2.6.9 and 2.7.0-rc.2
- Operating System: Mac OSX

<img width="1368" alt="Captura de Tela 2022-01-21 às 11 08 15" src="https://user-images.githubusercontent.com/92947335/150542852-72e11925-45cb-4474-81dd-167d8cfa5d79.png">

**Comment by wiliansilvazup** [comment]
Actually with the change of tool description the hash has changed.

For this scenario the change was based on the link `(https://ossindex.sonatype.org/vulnerability/...&utm_source=nancy-client&utm_medium=integration&utm_content=0.0.0-dev)` where in the query string they removed the `0.0.0-dev` for exactly the version of nancy we are running at `1.0.29`. For this case we decided to keep the new version as it may have important updates from the community that were not being exposed to the `0.0.0-dev` filter.
