### ISSUE TITLE
Duplicate key "accounts_email_key" on restarting docker service

### ISSUE THREAD

**Issue by cactuschibre** [ZupIT/horusec#955]
**What happened**:

After the fresh installation of Horusec Platform, when the Docker service is restarted containers fails to start.

**What you expected to happen**:

Horusec Plateform restarted successfully after Docker service restart.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
sudo docker service stop
sudo docker service start
```

**Anything else we need to know?**:

**Environment**:

- Horusec version (use `horusec version`):
```bash
horuszup/horusec-api:v2.16.4          
horuszup/horusec-analytic:v2.16.4     
horuszup/horusec-core:v2.16.4         
horuszup/horusec-messages:v2.16.4     
horuszup/horusec-webhook:v2.16.4      
horuszup/horusec-auth:v2.16.4         
horuszup/horusec-vulnerability:v2.16.4
postgres:12                           
horuszup/horusec-manager:v2.16.4      
```

- Operating System: Linux kali 5.10.0-kali5-amd64 ZupIT/horusec-platform#1 SMP Debian 5.10.24-1kali1 (2021-03-23) x86_64 GNU/Linux
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

Probably caused by the default configuration of horusec-auth ; docker logs of Postgres:
```bash
2021-08-17 07:08:06.255 UTC [37] ERROR:  duplicate key value violates unique constraint "accounts_email_key"
2021-08-17 07:08:06.255 UTC [37] DETAIL:  Key (email)=(dev@example.com) already exists.
2021-08-17 07:08:06.255 UTC [37] STATEMENT:  INSERT INTO "accounts" ("account_id","email","password","username","is_confirmed","is_application_admin","created_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
```
Possible workaround: set the environment variable `HORUSEC_ENABLE_DEFAULT_USER` to false in `compose.yaml`.

**Comment by nathanmartinszup** [comment]
This issue was fixed and will be available in the next release, so i will closing this issue.
