### ISSUE TITLE
web application does not work when deploying without localhost

### ISSUE THREAD

**Issue by py-paulo** [ZupIT/horusec#958]
I have a machine in the cloud and I deployed the application via docker-compose, I set the environment variables in the following ways:

![horusec_0x2](https://user-images.githubusercontent.com/71179739/146011821-3d4bbd77-f090-459d-8166-879dad6240dd.png)

but when I deploy, either using 'compose-dev' or 'compose' with 'make' (Makefile) the defined variables are not used, which generates the following error when accessing the web interface:

![horusec_0x1](https://user-images.githubusercontent.com/71179739/146012003-dc62c43b-bf7d-497b-b1bc-13a8ede29a93.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`):
- Operating System:
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by nathanmartinszup** [comment]
As the issue seems to be finished, I will close it. Any problems feel free to open it again.
