### ISSUE TITLE
Database password in plain text not warned for kotlin/micronaut api

### ISSUE THREAD

**Issue by guilhermepaulozup** [ZupIT/horusec#962]
**What happened**:
Built a simple REST API with Kotlin/Micronaut using POSTGRES container as database. The application.yml file is using a plain_text and very simple password ("123456) and Horusec CLI is not warning me about this issue.

src/main/resources/application.yml
![image](https://user-images.githubusercontent.com/90329628/151809386-52497d20-0b47-4a22-baaf-f11b63d8ef02.png)

**What you expected to happen**:
Horusec CLI should point out the issue of using the plain_text and simple password as a database password

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Kotlin/Micronaut application from the micronaut launch tool.
- Add Micronaut Data dependency.
- Add postgres driver
- Configure POSTGRES access with plain_text password in application.yml
- Run horusec CLI: ```horusec start``` on src folder.

**Anything else we need to know?**:
- Kotlin: v1.6.10
- Micronaut: v3.2.7

**Environment**:
- Horusec version (use `horusec version`): v2.6.8
- Operating System: Ubuntu 20.04 LTS
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others: Kotlin

**Comment by matheusalcantarazup** [comment]
Thanks for reporting @guilhermepaulozup
