### ISSUE TITLE
Windows bat script analyzed as shellscript

### ISSUE THREAD

**Issue by LG95** [ZupIT/horusec#976]
**What happened**:
I have a project with a Windows batch script (`.bat` file), that horusec analyzes as if it were shell script (`.sh` file) when running with the `--enable-shellcheck="true"` flag. However, these two scripting languages are incompatible and very different from one another.
Below is a snippet of an incompatible vulnerability, since it only considers shell script syntax.
```json
        "file": "script.bat",
        "details": "Use 'cd ... || exit' or 'cd ... || return' in case cd fails.",
        "securityTool": "ShellCheck",
        "language": "Shell",
```

**What you expected to happen**:
Windows batch scripts to be not be analyzed as shell script.

**How to reproduce it (as minimally and precisely as possible)**:
Create a test.bat file that contains the following line and analyze it with `horusec start --enable-shellcheck="true`.
```bat
cd Downloads
```

**Anything else we need to know?**:

**Environment**:
- Horusec version (use `horusec version`): 2.6.9
- Operating System: Ubuntu 20.04
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by wiliansilvazup** [comment]
Hello @LG95 thanks for your contribution. Really, this is an unexpected behavior, we will check, any news we will inform you here.

**Comment by wiliansilvazup** [comment]
@LG95 I executed tests on horusec-cli in version `v2.7.0` and i received this output
![image](https://user-images.githubusercontent.com/63816070/153190214-72791233-03b5-4646-a4b8-75a46d982a03.png)

Try [update your horusec](https://docs.horusec.io/docs/cli/installation/) to latest version to check if the problem was resolved.

**Comment by LG95** [comment]
Hi @wiliansilvazup I reran the tests with the latest Horusec version, and unlike your execution, with a single low vulnerability the analysis results in error. I am running `horusec start --enable-shellcheck="true" --project-path="./"`. But I also looked into Windows batch syntax and found that the suggestion is actually valid syntax, so it is actually a valid vulnerability.
Thanks for the attention!

**Comment by LG95** [comment]
@matheusalcantarazup it is the same steps as described in this issue, I believe this image helps.
![image](https://user-images.githubusercontent.com/9141516/153917839-98eb4574-0b28-440c-822e-5976ac077bb5.png)
