### ISSUE TITLE
Version 2.7 Scans exiting

### ISSUE THREAD

**Issue by seanpclayton** [ZupIT/horusec#984]
**What happened**: Git cloned a repository to run Horusec against; exited with `Error: open /Users/sean/FOLDER/.horusec/2d2ff837-bb11-4b49-ae19-169ba9176bf7/SafeMart.Utilities.Pdf/Converter.cs: no such file or directory`

**What you expected to happen**: I did not expect that error

**How to reproduce it (as minimally and precisely as possible)**: After repository clone, download and install latest version of Horusec; Run `Horusec generate`; vim or nano into "./output.json" and set horusecCliPrintOutputType: "json"; increase time limits; run `Horusec start`

**Anything else we need to know?**: Error does not happen with version 2.6.9

**Environment**:
- Horusec version (use `horusec version`):2.7.0
- Operating System: Mac Monterrey 12.1
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by iancardosozup** [comment]
ty for you feedback, we'll try to fix it as soon as possible.
To make more easy to find your problem can you upload your config file, the exactly command you've runned and the full log after command runned?

**Comment by iancardosozup** [comment]
closing since there was no response, @seanpclayton you can reopen it when you answer my questions
