### ISSUE TITLE
Problems when sent a analisis to web manager in a another host.

### ISSUE THREAD

**Issue by dschacon288** [ZupIT/horusec#994]
**What happened**:
I install the web manager in another host i am trying run a analysis and sent it, but  the analysis dont show in web manager
**How to reproduce it (as minimally and precisely as possible)**:
install horusec manager  in another host.
Run a analisis and put the flag -u whit the ip where manager are located and the token
Web manager dont show the analisys 
**Anything else we need to know?**:
How to know what is the error, because, the anlysis dont show if the conection was succesfull 
**Environment**:
- Horusec version : V2.0
- Operating System:  kali linux
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others: instalation whit docker and docker compose

**Comment by wiliansilvazup** [comment]
Hello @dschacon288 tnks for report.

Is not clear for me the Version. Do you can sent again what is version:
- Horusec-CLI 
- Horusec-Platform micro services

**Comment by dschacon288** [comment]
version is Horusec-Platform micro services, but i dont know if the cli sent the analysis because never lauch a confirmacion, when the cli have a issue to sent the analisis have a alert

**Comment by wiliansilvazup** [comment]
Ok.
Horusec-Platform service is in v2.0.0, correct ?

Now, run `horusec version` in your terminal and sent me what is your version of the Horusec-CLI.

Show me prints or errors when you sent analysis too, this help me to understand the problem :)

**Comment by dschacon288** [comment]
The version:
![image](https://user-images.githubusercontent.com/31111885/154522160-d8b4e5b8-8d83-4a7b-8964-7f32b346c591.png)
There is no error message or confirmation that the analysis has been sent, but the analysis does not appear on the web.
![image](https://user-images.githubusercontent.com/31111885/154523921-401c8097-7888-404b-a11e-be0459d9f1aa.png)

**Comment by dschacon288** [comment]
1. Log file
![image](https://user-images.githubusercontent.com/31111885/154537392-c2ae8f04-4d49-4021-aa1d-990a04c84786.png)
2. Sevices runing
![image](https://user-images.githubusercontent.com/31111885/154537500-a12c35bb-635f-42c9-89ed-cb62ab83fb3c.png)
3. logs docker horusec-api
![image](https://user-images.githubusercontent.com/31111885/154536852-681b9523-c372-4e33-9684-90e401ffe3e8.png)

**Comment by dschacon288** [comment]
![image](https://user-images.githubusercontent.com/31111885/154538410-2b457b3f-a527-4d00-a048-e6f202a3fbc3.png)

this is the horusec start log

**Comment by dschacon288** [comment]
Well, i clean the horuseg-confif.json and use the variable enviroment, so the result was this:
![image](https://user-images.githubusercontent.com/31111885/154555336-b9a6c3f3-aa5d-4086-a3e1-52b5d6e74327.png)
in this image, show de id of analisis
![image](https://user-images.githubusercontent.com/31111885/154555544-5e33abad-28c0-4a9d-ba45-59376149e0e4.png)
and finally the result of analisis
![image](https://user-images.githubusercontent.com/31111885/154555743-1938041a-8d14-4547-9778-665c8d7f618b.png)

so, I think  that the problem is in the database of web manager, because in logs of docker horusec-api show that he send a analysys to host and recive a 201 status code. but I dont undertstand why make a get  
![image](https://user-images.githubusercontent.com/31111885/154556450-b7970480-ed1c-4db1-b4fe-b88a9d87c532.png)

**Comment by wiliansilvazup** [comment]
The GET has necessary in Horusec-CLI to merge all false-positives in web application and show in your analysis locally.

Well, your analysis is being saved successfully. And when you go into your browser and access the Horusec-Manager application, it doesn't show any vulnerability on the Dashboard screen or on the Vulnerability Manager screen?

**Comment by wiliansilvazup** [comment]
Try access Dashboard screen in your browser and show me logs of the Horusec-Analytic service.

**Comment by dschacon288** [comment]
This is the log of analytic services
![image](https://user-images.githubusercontent.com/31111885/154692344-da2c2565-8099-47a4-8cf9-ba1f9f1da43d.png)

In the browser the dashboard are empty but the vulnerability no
![image](https://user-images.githubusercontent.com/31111885/154692696-296ee0c7-7e9f-4de5-a409-ad68c8104199.png)

Vulnerabilities
![image](https://user-images.githubusercontent.com/31111885/154692848-a96928d9-d3d3-436a-aef7-4484a7f09c64.png)

**Comment by wiliansilvazup** [comment]
This is really strange.

You can access the analytic database and check if there is recorded data in any table?

**Comment by dschacon288** [comment]
Well, we have these db
![image](https://user-images.githubusercontent.com/31111885/155002541-ed5f0ea6-25da-421c-8ff0-00b66e83c61d.png)

we are only interested in the first two

the analytic db have records
![image](https://user-images.githubusercontent.com/31111885/155002997-71f9e9ae-9838-4ae3-b200-631ed29fadf0.png)

consulting data
![image](https://user-images.githubusercontent.com/31111885/155003694-1e17de49-7b7c-430a-a079-4fc11508d464.png)

and in horusec_db too

![image](https://user-images.githubusercontent.com/31111885/155004016-85204833-b58f-4089-925c-d58921cf8b0f.png)

In the web, appear a error in the dashboard network

![image](https://user-images.githubusercontent.com/31111885/155004147-f6d60a32-988f-462b-81a7-ca5fb1265a14.png)

**Comment by wiliansilvazup** [comment]
wow i think i found the problem :)

Your Configuration in Horusec-Manager micro-service is wrong. The port correct of the horusec-analytic is `8005`.

Change this environment variable in Horusec-Manager to:
`HORUSEC_ENDPOINT_ANALYTIC = https:\\/\\/:192.168.145.129:8005`

and try again

**Comment by dschacon288** [comment]
In effect, there is the problem. Now is all correct 

I have a last question, when i try to run a analisis into pipeline of azure devops. I have this error, maybe you know how to fix it
![image](https://user-images.githubusercontent.com/31111885/155011361-5e3a678f-d24b-4b3b-9afc-c27106ad01e6.png)
